### ISSUE TITLE
Data loss

### ISSUE THREAD

**Issue by Rammun** [WorkMaze/JUST.net#1]
How in the transformation does not lose the time zone?
`{ "SendDate": "2017-04-26T19:27:00+03:00" } `
After the transformation
`{ "SendDate": "26.04.2017 19:27:00 }`

**Comment by WorkMaze** [comment]
Hi,
Thanks for your feedback. Please send me the input JSON and the transformer JSON and I shall investigate it.
Regards.

**Comment by Rammun** [comment]
Hi,

input string
```
{	
	"ExternId":"12345",
	"EventTypeId":"21",
	"EventSysId":"2",
	"SendDate":"2017-04-10T11:36:39+03:00",
	"Name":"Petr",
	"Surname":"Petrov",
	"Patronymic":"Petrovich",
	"BirthDate":"1984-02-02T00:00:00+02:00"
}
```
and output
```
{
	"ExternId":"12345",
	"EventTypeId":"21",
	"EventSysId":"2",
	"SendDate":"10.04.2017 11:36:39",
	"Name":"Petr",
	"Surname":"Petrov",
	"Patronymic":"Petrovich",
	"BirthDate":"02.02.1984 1:00:00"
}

```

**Comment by WorkMaze** [comment]
Hi again,
The transformer JSON?

**Comment by Rammun** [comment]
Corrected the message

**Comment by WorkMaze** [comment]
I have published a new nuget package - 1.0.7. Please use that one and let me know how the results look.
Thanks!

**Comment by Rammun** [comment]
Thanks for the answer, but the time zone is lost. Know the time zone is important to me.

input
```
{
	"ExternId":"12345",
	"EventTypeId":"21",
	"EventSysId":"2",
	"SendDate":"2017-04-10T11:36:39+01:00",
	"Name":"Petr",
	"Surname":"Petrov",
	"Patronymic":"Petrovich",
	"BirthDate":"1984-02-02T01:00:00+02:00"
}
```

output
```
{
	"ExternId":"12345",
	"EventTypeId":"21",
	"EventSysId":"2",
	"SendDate":"2017-04-10T13:36:39+03:00",
	"Name":"Petr",
	"Surname":"Petrov",
	"Patronymic":"Petrovich",
	"BirthDate":"1984-02-02T02:00:00+03:00"
}
```

**Comment by WorkMaze** [comment]
Hi,
I made another fix. Please use the latest nuget -1.0.8.
Thanks!

**Comment by Rammun** [comment]
It works. Thanks for a quick fix. Your library helped to solve my task.

**Comment by WorkMaze** [comment]
Good to know! Please feel free to contact me again if you find anything.
I am closing this issue for now.
Best regards!
