### ISSUE TITLE
values that start with # gets exception for #currentvalueatpath

### ISSUE THREAD

**Issue by jan-iqbo** [WorkMaze/JUST.net#100]
input
`[{"sample1":"#s1_value","sample2":"s2_value"}]`

transformer
`{
	"x": {
		"#loop($)": {
			"x_sample1": "#currentvalueatpath($.sample1)",
			"x_sample2": "#currentvalueatpath($.sample2)"
		}
	}
}`

exception
`'Error while calling function : #s1_value - Length cannot be less than zero. (Parameter 'length')'
`

**Comment by Courela** [comment]
Which version are you using?

**Comment by jan-iqbo** [comment]
I am using an old version but tried it also in the latest downloadable
version from Nuget 3.0.6. Both have this issue

--

**Comment by Courela** [comment]
I've tried your example and it works just fine.

**Comment by jan-iqbo** [comment]
Yes, it works on the latest. My versions just got mixed up. Thanks!
