### ISSUE TITLE
Int to string

### ISSUE THREAD

**Issue by Rammun** [WorkMaze/JUST.net#12]
Hi,
how can I convert int to string?

the input: 
{
   "Id": 123
}

I would like to get out
{
    "Id": "123"
}

It doesnt work
{
    "Id": "\\"#valueof($.Id)\\""
}

**Comment by WorkMaze** [comment]
Hi,
For this particular problem - Converting INT to STRING, the below transformation will work.

`{
  "Id": "#xconcat(\",#valueof($.Id),\")"
}`

Regards!

**Comment by Rammun** [comment]
Ок. Thanks for the answer!
