### ISSUE TITLE
[Question] Sort of fields not kept in transformation when conditions are applied

### ISSUE THREAD

**Issue by mathieumack** [WorkMaze/JUST.net#122]
Hi,
In a transformation, all fields defined in the transformation with a condition (#ifgroup, ...) are always inserted at the end of Jtokens.
Ex transformation : 
`{
    "array_result": {
      "#loop($.arrayInput)": {
        "#ifgroup(<condition>)": {
          "samplefield": {
            ...
          }
        },
        "field1": "Value 1"
      }
  }
}`
Output :
`{
    "array_result": [
        {
            "field1": "Value 1",
            "sampleField": "sampleValue"
        }
    ]
}`
Expected :
`{
    "array_result": [
        {
            "sampleField": "sampleValue",
            "field1": "Value 1"
        }
    ]
}`

Is there a way do keep sort of fields defined in the transformation ?

**Comment by mathieumack** [comment]
By reading the source code it's by design, but perhaps that there is a way to write my condition in order to avoid my #ifgroup at root level.

**Comment by Courela** [comment]
JSON does not require that the fields' order is preserved.

**Comment by mathieumack** [comment]
Yes I know and I'm ok with that, I just ask if there a possibility to manage this part.
For example, depending on parser implemented that read my generated json content, we can imagine that developpers needs to validate sort of fields if I add new fields for example (like a WSDL operation, fields order is important by default).
