### ISSUE TITLE
xconcat method does not work

### ISSUE THREAD

**Issue by Rammun** [WorkMaze/JUST.net#13]
Since version 4.02 the xconcat method does not work
`System.Exception: Error while calling function : #xconcat(#valueof($.Model))`

**Comment by WorkMaze** [comment]
Hmmm...it seems to work for the case I am testing. Could you paste the input and the transformer for which it is throwing this error?
Thanks!

**Comment by Rammun** [comment]
It seems that the problem is not in the method, but in the processing of fields that are not present in the incoming model. Previously, this was done correctly. Now falls with an error.

**Comment by Rammun** [comment]
If it does not find a field, let it return null, not an exception.

**Comment by Rammun** [comment]
In my opinion, When concatenating, it will be adequate to return an empty string if the field does not exist

**Comment by WorkMaze** [comment]
Hi, I have published a new version 4.0.5. That should fix this problem.
Regards!

**Comment by Rammun** [comment]
Now the expected old behavior. Thank you very much.
