### ISSUE TITLE
Loop alias is required and it shouldn't be

### ISSUE THREAD

**Issue by Courela** [WorkMaze/JUST.net#134]
When assigning an alias to a loop, every function inside a loop must have a reference to that alias, instead of falling back to the last loop.

**Comment by Jay-MacDonald** [comment]
I am also having an issue with loops. I just updated my JUST.net Nuget package and suddenly my mapping files don't work. 

Is the "#loopwithincontext" gone now? I am getting errors like this: 

`Error while calling function : #currentvalueatpath($.Cd) - Object reference not set to an instance of an object.`

The section in my mapping file looks like this: 
![image](https://user-images.githubusercontent.com/39162227/109306194-36903980-7815-11eb-8ec1-d337eba7c90d.png)

**Comment by Courela** [comment]
#loopwithincontext doesn't exist anymore, now you can have as many nested #loops as you want.
