### ISSUE TITLE
Support for nested loops

### ISSUE THREAD

**Issue by lemmit** [WorkMaze/JUST.net#14]
Is there a way to create a nested loop?
#loop(#currentvalueofpath(...)) ends with "Unexpected character while parsing path indexer: $”" error.

**Comment by WorkMaze** [comment]
Hi,
#loop() functions takes the JSON path as the argument. A function (#currentvalueofpath(...)) is an invalid argument to the function. Could you send across the input JSON & the expected JSON, so that I can get an insight of what you are trying to achieve and see if that is possible I the current solution?
Thanks!

**Comment by WorkMaze** [comment]
Hi again, 
I have added support for nesting of loops now. The latest Nuget 4.0.7 (1.2.8 for .NET Core), support it.

Input:
`{
  "Organization": {
    "Employee": [
      {
        "Name" :  "E2",
        "Details": [
          {
            "Country": "Iceland",
            "Age": "30",
            "Name": "Sven",
            "Language": "Icelandic"
          }
        ]
      },
      {"Name" :  "E1",
        "Details": [
          {
            "Country": "Denmark",
            "Age": "30",
            "Name": "Svein",
            "Language": "Danish"
          }
        ]
      }
    ]
  }
}`

Transformer:
`{  
    "hello": {
      "#loop($.Organization.Employee)": {
        "CurrentName": "#currentvalueatpath($.Name)",
        "Details" :
        {
          "#loop($.Details)": {
            "CurrentCountry": "#currentvalueatpath($.Country)" 
          }
        }
      }
    }  
 }`

Output:
`{  
   "hello":[  
      {  
         "CurrentName":"E2",
         "Details":[  
            {  
               "CurrentCountry":"Iceland"
            }
         ]
      },
      {  
         "CurrentName":"E1",
         "Details":[  
            {  
               "CurrentCountry":"Denmark"
            }
         ]
      }
   ]
}`

Please let me know if you are able to use this feature or was it something else you were looking for.
Regards!

**Comment by lemmit** [comment]
That's it! I'm delighted of the project support!
One thing to consider:
That fix changes slightly the previous behaviour. Loop like that would work like a loop on the main context (and create join-like experience). Shouldn't it be left like it was and some other operator like loopatpath introduced?

**Comment by WorkMaze** [comment]
Hi,
So if I understand you correctly, you want to be able to loop both in the context of the original input as well in the context of the currently looped array?
And that is the reason you proposed two separate functions. Is that correct?

**Comment by lemmit** [comment]
The syntax that is now used for inner loop, was previously valid syntax for creating a product of two arrays.
Some users can experience unexpected errors after update  - that is a breaking change.
Shouldn't this be described in the release notes? Or function with different name should be created for the loop over property in inner context (my initial idea)?

Nested looping already works. From my perspective the issue can be closed. I just wanted to point out that it can be problem for someone else.

**Comment by WorkMaze** [comment]
Hmmm. ok then I understand. 

You are right, this might be a breaking change for other users. I will leave this issue open for now and will come up with a solution.

As you suggested, I shall undo the changes I did to the 'loop' function and will introduce a new function 'loopwithincontext'.

**Comment by WorkMaze** [comment]
Hi again,
I have reverted the changes for 'loop' and added 'loopwithincontext'.

Your transformer therefore will look like 
`{
  "hello": {
    "#loop($.NestedLoop.Organization.Employee)": {
      "CurrentName": "#currentvalueatpath($.Name)",
      "Details": {
        "#loopwithincontext($.Details)": {
          "CurrentCountry": "#currentvalueatpath($.Country)"
        }
      }
    }
  }
}`

Please get the latest version(s) & thank you for pointing this out.
Regards!
