### ISSUE TITLE
Problem with an array selector when looping

### ISSUE THREAD

**Issue by lemmit** [WorkMaze/JUST.net#15]
For a given JSON:
```json
{
 "SomeObject": [
  {
   "State": "A"
  },
  {
   "State": "B"
  }
 ]
}
```
the JSONPath $.SomeObject[*] returns:
```json
[
  {
    "State": "A"
  },
  {
    "State": "B"
  }
]
```
which is an array.

The transformer yields an error „Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'Newtonsoft.Json.Linq.JArray'.”
Any idea why it happens? I have double checked the path in the evaluator, and it seems to work fine.
When I removed the [*] it seems to work fine. Also, when the value is not found, the NullPointerException occurs. What to do when the field on which I am looping is not mandatory?

**Comment by lemmit** [comment]
Having in mind the second issue I created [https://github.com/WorkMaze/JUST.net/issues/14](url) I will explain what I wanted to achieve.
Input json:
```json
{
  "people": [
      {
        "name": "Jim",
        "phoneNumbers": [
        {
          "type"  : "iPhone",
          "number": "0123-4567-8888"
        },
        {
          "type"  : "work",
          "number": "012567-8910"
        }
      ]
    },
    {
        "name": "John",
        "phoneNumbers": [
        {
          "type"  : "iPhone",
          "number": "0123-4562347-8888"
        },
        {
          "type"  : "home",
          "number": "0134523-4567-8910"
        }
      ]
    },
    {
        "name": "John"
    }
  ]
}
```
And then create foreach loop at the people level ($.people[*]) and then on the phone numbers level ($.phoneNumbers[?(@.type == 'iPhone')]).

I need to make a loop to use some additional functions and conditions on each level. Without [*] and condition for phone type it works ok. When some filtering occurs or * is specified, the transformer breaks.

**Comment by WorkMaze** [comment]
Hi, response to your first comment.
If you use the transformer:
`{
  "hello": "#valueof($.SomeObject)"
}`

You get the output:
`{"hello":[{"State":"A"},{"State":"B"}]}`

**Comment by lemmit** [comment]
Yes, but still the standard JSONPath that returns array should work. [*] was the simplest case, that's why I have made the second comment to show what I want to achieve (filtering).

**Comment by WorkMaze** [comment]
What is the transformer you are using? The output of a transformation is always a JSON object. A JSON array output is not yet supported.

**Comment by WorkMaze** [comment]
With regards to your second comment. I have made a scenario.

Input:
`{
  "people": [
      {
        "name": "Jim",
        "phoneNumbers": [
          {
            "type": "iPhone",
            "number": "0123-4567-8888"
          },
        {
          "type"  : "work",
          "number": "012567-8910"
        }
      ]
    },
    {
        "name": "John",
        "phoneNumbers": [
        {
          "type"  : "iPhone",
          "number": "0123-4562347-8888"
        },
        {
          "type"  : "home",
          "number": "0134523-4567-8910"
        }
      ]
    }
  ]
}`

Transformer:
`{
  "iPeople": {
    "#loop($.people)": {
      "iName": "#currentvalueatpath($.name)",
      "iPhone": {
        "#loop($.phoneNumbers)": {
          "CurrentNumber": "#currentvalueatpath($.number)",
          "IsIPhone": "#ifcondition(#firstindexof(#currentvalueatpath($.type),i),-1,Not a good phone,An iPhone) "
        }
      }
    }
  }
}`

Output:
`{"iPeople":[{"iName":"Jim","iPhone":[{"CurrentNumber":"0123-4567-8888","IsIPhone":"An iPhone"},{"CurrentNumber":"012567-8910","IsIPhone":"Not a good phone"}]},{"iName":"John","iPhone":[{"CurrentNumber":"0123-4562347-8888","IsIPhone":"An iPhone"},{"CurrentNumber":"0134523-4567-8910","IsIPhone":"Not a good phone"}]}]}`

This is how the looping(nested looping) works at the moment. It is possible that you are trying to do something more complex which might not be possible at the moment.

In that case, could you send across your input, transformation and the expected result? I shall definitely add new features if required.

Regards!

**Comment by lemmit** [comment]
Input:
```json
{
  "people": [
      {
        "name": "Jim",
        "phoneNumbers": [
        {
          "type"  : "iPhone",
          "number": "0123-4567-8888",
          "countryPrefix: "34"
        },
        {
          "type"  : "work",
          "number": "012567-8910"
        }
      ]
    },
    {
        "name": "John",
        "phoneNumbers": [
        {
          "type"  : "iPhone",
          "number": "0123-4562347-8888",
          "countryPrefix: "43"
        },
        {
          "type"  : "home",
          "number": "0134523-4567-8910"
        }
      ]
    },
    {
        "name": "John"
    }
  ]
}
```

Transformer:
```json
{
 "iPhoneNumbers":
    "#loop($.people.phoneNumbers[?(@.type=='iPhone')]" : {
       "phoneNumber": "#concat(#currentvalueatpath($.countryPrefix), #currentvalueatpath($.number))"
    }
}
```
Desired output:
```json
{
  "iPhoneNumbers": [ { phoneNumber: "340123-4567-8888"}, { phoneNumber: "430123-4562347-8888"}]
}
```

I still believe that is an issue with the filtering using the JSONPath...

**Comment by WorkMaze** [comment]
Hi, This is a bit more complicated issue. I will have to get back to you on this.

**Comment by WorkMaze** [comment]
Hi again,
The path you entered was not returning at tokens. I have made a small fix and uploaded the latest version.

You will get your desired output using the following transformation now:-

`{
  "iPhoneNumbers": {
    "#loop($.people[?(@.phoneNumbers[0].type =='iPhone')]]": {
      "phoneNumber": "#concat(#currentvalueatpath($.phoneNumbers[0].countryPrefix), #currentvalueatpath($.phoneNumbers[0].number))"
    }
  }
}`

This is just a quick fix. I will look into how t make this more generic.
Regards!

**Comment by lemmit** [comment]
Sorry, my mistake with the selector, it should be with [*] in that example. So the transformer I wanted to use was:
```json
{
 "iPhoneNumbers": {
    "#loop($.people[*].phoneNumbers[?(@.type=='iPhone')]" : {
       "phoneNumber": "#concat(#currentvalueatpath($.countryPrefix), #currentvalueatpath($.number))"
    }
 }
}
```

The online evaluators show me that any of the given selectors returns an array of values (which I would like to iterate over):
$.people[*]
$.people[*].phoneNumbers[?(@.type=='iPhone')]
$.people[?(@.name=='Jim')].phoneNumbers[?(@.type=='iPhone')]

What I finally would like to do is iterate over $.people[*] or $.people[?(@.name=='Jim')], and then inside the inner loop over $.phoneNumbers[?@(.type=='iPhone')]. That would alllow me to have full control of the transformation withing different scopes.

**Comment by lemmit** [comment]
I have tested everything after the update once again.
I see now what is going on. The errors seem to be thrown in 2 situations:
1. The selector returns an array of 1 element. If I use the selector like this:
```json
$.people[?(@.name=='Jim' || @.name=='John')].phoneNumbers[?(@.type=='iPhone')]
```
it works fine.  When I leave only Jim, it ends up with casting exception (JObject -> JArray).
2. When there is no elements returned somewhere on the way it causes NullPointerException:
```json
$.people[?(@.name=='DoesntExistsAtAll')].phoneNumbers[?(@.type=='iPhone')]
```

In both cases it should "Just work" and return some kind of the null object (empty array, empty object, no iterate at all when there is no elements).

P.S. You are doing great job here :)

**Comment by WorkMaze** [comment]
Hi,

I think  (I hope) my latest fix should solve the issues you are having. Please download the latest Nuget 4.0.10 (1.2.11 for .NET Core).

Input:
`{
  "people": [
      {
        "name": "Jim",
        "phoneNumbers": [
        {
          "type"  : "iPhone",
          "number": "0123-4567-8888",
          "countryPrefix": "34"
        },
        {
          "type"  : "work",
          "number": "012567-8910"
        }
      ]
    },
    {
        "name": "John",
        "phoneNumbers": [
        {
          "type"  : "iPhone",
          "number": "0123-4562347-8888",
          "countryPrefix": "43"
        },
          {
            "type": "home",
            "number": "0134523-4567-8910"
          }
      ]
    },
    {
        "name": "John"
    }
  ]
}`

Transformer:
`{
  "iPhoneNumbers1": {
    "#loop($.people[*].phoneNumbers[?(@.type=='iPhone')])": {
      "phoneNumber": "#concat(#currentvalueatpath($.countryPrefix), #currentvalueatpath($.number))"
    }
  },
  "iPhoneNumbers2": {
    "#loop($.people[?(@.name=='Jim' || @.name=='John')].phoneNumbers[?(@.type=='iPhone')])": {
      "phoneNumber": "#concat(#currentvalueatpath($.countryPrefix), #currentvalueatpath($.number))"
    }
  },
  "iPhoneNumbers3": {
    "#loop($.people[?(@.name=='Jim1' || @.name=='John')].phoneNumbers[?(@.type=='iPhone')])": {
      "phoneNumber": "#concat(#currentvalueatpath($.countryPrefix), #currentvalueatpath($.number))"
    }
  },
  "iPhoneNumbers4": {
    "#loop($.people[?(@.name=='Jim1' || @.name=='John1')].phoneNumbers[?(@.type=='iPhone')])": {
      "phoneNumber": "#concat(#currentvalueatpath($.countryPrefix), #currentvalueatpath($.number))"
    }
  }
}`

Output:
`{  
   "iPhoneNumbers1":[  
      {  
         "phoneNumber":"340123-4567-8888"
      },
      {  
         "phoneNumber":"430123-4562347-8888"
      }
   ],
   "iPhoneNumbers2":[  
      {  
         "phoneNumber":"340123-4567-8888"
      },
      {  
         "phoneNumber":"430123-4562347-8888"
      }
   ],
   "iPhoneNumbers3":[  
      {  
         "phoneNumber":"430123-4562347-8888"
      }
   ],
   "iPhoneNumbers4":[ ]
}`

Regards!

**Comment by lemmit** [comment]
Works as a charm! Thanks!
