### ISSUE TITLE
How to return JArray from a custom function

### ISSUE THREAD

**Issue by ganeshthiagarajan** [WorkMaze/JUST.net#151]
We have a situation where we need to apply multiple checks from different nodes to arrive at an array result. We are using custom function to achieve it considering the complexity of the work. What should the custom function return so it can be mapped as an array element in the json. If we return a JArray from the custom function, will it be mapped correctly?

**Comment by Courela** [comment]
I think so, it is stored as an object so it should do it.
If you use the .Transform() method that returns a string, as long as .ToString() method returns what you want, you should be ok.

**Comment by ganeshthiagarajan** [comment]
Thank you for coming back on this @Courela , it did work like charm, I will close the issue.
