### ISSUE TITLE
AGPL dependency may not be used with MIT License

### ISSUE THREAD

**Issue by steurer** [WorkMaze/JUST.net#152]
JUST.net references Newtonsoft.Json.Schema which is licensed under AGPL (or commercial license) and therefore not compatible with the MIT License.

JUST.net may not be distributed under MIT License and can currently not be used in closed-source software because it contains a transitive dependency to an AGPL-licensed library.

IANAL, so this is only my laymans understanding of these licenses.

Is it possible to replace Newtonsoft.Json.Schema with a MIT-licensed library (e.g. NJsonSchema)?

**Comment by Courela** [comment]
Ups... I wasn't aware of that. I don't use schema validator, so I never looked at it. 
It seems possible to replace Newtonsoft.Json.Schema with NJsonSchema thou, I'll have to do it in order to continue using this software. Possibly the messages won't be the same...
