### ISSUE TITLE
Error when property value has a comma.

### ISSUE THREAD

**Issue by gsantana** [WorkMaze/JUST.net#154]
Source:
{
   "autofac":{
      "defaultAssembly":"Component.Just.Test",
      "components":[
         {
            "type":"Component.Just.Test, Component.Just",
            "services":[
               {
                  "type":"Component.Just.ITest, Component.Just"
               }
            ]
         }
      ]
   }
}

Target:

{
   "autofac":{
      "defaultAssembly":"Component.Just.Test",
      "components":[
         {
            "type":"Component.Just.Test2, Component.Just",
            "services":[
               {
                  "type":"Component.Just.ITest, Component.Just"
               }
            ]
         }
      ]
   }
}

Transform File:

{
    "#": ["#copy($)",
		  "#replace($.autofac.components[?(@.type == 'Component.Just.Test/, Component.Just')].type,Component.Just.Test2/, Component.Just)"
         ]
}

Error:
Exception non gérée : System.Exception: #replace needs exactly two arguments - 1. xpath to be replaced, 2. token to replace with.
   à JUST.JsonTransformer.GetTokenStringToReplace(String inputString)
   à JUST.JsonTransformer.RecursiveEvaluate(JToken parentToken, String inputJson, JArray parentArray, JToken currentArrayToken)
   à JUST.JsonTransformer.Transform(String transformerJson, String inputJson)
   
   
 The transform file doesn't seem to work because of the comma in the  property value, even if I use escape.
 Is there a way around this?
 I use version 5.1.3

Thanks

**Comment by gsantana** [comment]
I'm using this package https://www.nuget.org/packages/JUST/, version 5.3.1,
Is it the same as JUST.NETCore?

Thanks,

**Comment by Courela** [comment]
Sorry, JUST package was for .Net framework only, JUST.NETCore was for .Net Core.
Now there's only one package that works for both, [JUST.Net](https://www.nuget.org/packages/JUST.net/)

**Comment by gsantana** [comment]
Thanks for your help.
