### ISSUE TITLE
Consider releasing the source code

### ISSUE THREAD

**Issue by lemmit** [WorkMaze/JUST.net#16]
The project seems to be extremely promising. I'd definitely contribute to it. Is there any plans of releasing the source code?

**Comment by WorkMaze** [comment]
Thanks for the suggestions. I am definitely considering releasing the source code. I haven't planned it yet but I shall soon. At the moment I am just trying to help the users fix their issues. Once I feel relatively confident, I will add comments and structure the code a bit more & then definitely release it.

I have had good feedback so far, so definitely I would appreciate if others can contribute to it.

**Comment by lemmit** [comment]
It actually can be a very limiting (for me as well) that the source is not opened.

If you are looking for a way to structure the code, probably the Interpreter Pattern is what you should think of. This is the perfect case to use it.

**Comment by Rammun** [comment]
Hi, If the code will open, I am also ready to contribute. Our project is dependent on this library, so I'm interested.

**Comment by WorkMaze** [comment]
Source code is available now.
