### ISSUE TITLE
Async custom functions

### ISSUE THREAD

**Issue by kakins** [WorkMaze/JUST.net#166]
Is it possible to write async custom functions?  It seems if I define an `async static Task<T>` method, it will be called, but the result fails to be returned in the transform

**Comment by Courela** [comment]
I never tried it, but it doesn't seem possible, or even handy? 
Why would you wanted to postpone the transformation? It makes sense to me postpone the result of the transformation, but after the transformation is done, not during.

**Comment by kakins** [comment]
Just trying to think through my particular use case.  I'm thinking about the possibility of using a custom function to call a remote endpoint, and get some data back as part of the transformation.  That led me to wonder if I use the synchronous or asynchronous methods on `HttpClient`.  I assumed I would try using the async methods for the same performance reasons I would use them in an asp.net project.

**Comment by Courela** [comment]
In that case, your custom function would have to be synchronous and wait for the result of HttpClient, even though the method you call in HttpClient may be asynchronous.

**Comment by kakins** [comment]
Very good, that answers my question here.  Thank you!
