### ISSUE TITLE
Use the function inside of the JSONPath expression

### ISSUE THREAD

**Issue by lemmit** [WorkMaze/JUST.net#17]
Consider such a construction somewhere inside a loop:
```json
someProp: #valueat($.someGlobalData[?(@.id==#currentvalueatpath($.id))])
```
That would allow me to achieve relational-like mapping!
From what I see it doesn't have to be very hard.
You can count the '[' and '(' and start evaluation of the # functions from the "deepest" place.
We can assume that those functions returns a simple value here...

**Comment by WorkMaze** [comment]
Hi, Yet another version released - 4.0.11(1.2.12).

Input: 
`{
  "PhoneTypeToSearch": "iPhone",
  "people": [
    {
      "name": "Jim",
      "phoneNumbers": [
        {
          "type": "iPhone",
          "number": "0123-4567-8888",
          "countryPrefix": "34"
        },
        {
          "type": "work",
          "number": "012567-8910"
        }
      ]
    },
    {
      "name": "John",
      "phoneNumbers": [
        {
          "type": "iPhone",
          "number": "0123-4562347-8888",
          "countryPrefix": "43"
        },
        {
          "type": "home",
          "number": "0134523-4567-8910"
        }
      ]
    },
    {
      "name": "John"
    }
  ],
}`

Transformer:
`{
  "iPhoneNumbers1": {
    "#loop($.people[*].phoneNumbers[?(@.type== '#valueof($.PhoneTypeToSearch)')])": {
      "phoneNumber": "#concat(#currentvalueatpath($.countryPrefix), #currentvalueatpath($.number))"
    }
  }
}`

Output:
`{  
   "iPhoneNumbers1":[  
      {  
         "phoneNumber":"340123-4567-8888"
      },
      {  
         "phoneNumber":"430123-4562347-8888"
      }
   ]
}`

I wasn't quite sure if this is what you wanted, but this still could be an interesting feature.
Regards!
