### ISSUE TITLE
#xconcat extracting the string #valueof($.id) instead of the actual value of the parameter

### ISSUE THREAD

**Issue by aagarwallaMS** [WorkMaze/JUST.net#183]
While using #xconcat along with the reserved characters, the #valueof function is treated as a string instead of a function. 
I have used the same example given in the **Escaping reserved characters** to use the reserved characters along with xconcat:
![image](https://user-images.githubusercontent.com/92075713/139566528-9a021e7d-0882-47c8-ac4a-93bb0ca9f3a4.png)

The exact code used and its output:
```
code: "#xconcat(func/(,#valueof($.id), /))"
output: "func/(,#valueof($.id), /)"
```

If I don't use the '/(' characters, then #valueof works fine inside #xconcat.

**Comment by Courela** [comment]
It seems to work fine in [4.2.0](https://www.nuget.org/packages/JUST.net/), which version so you use?

**Comment by aagarwallaMS** [comment]
Hey, I am using version 5.1.3

**Comment by Courela** [comment]
That's JUST.Net Core, a package that is not maintained anymore, use [JUST.Net](https://www.nuget.org/packages/JUST.net/), a package that works both in .Net Framework and .Net Core

**Comment by aagarwallaMS** [comment]
Okay, thank you so much. I'll update and try it out.

**Comment by aagarwallaMS** [comment]
When I update to JUST.Net, it gives me _**Unable to find package NJsonSchema with version >=10.4.1**_ error.
I am not able to install this package. Could you help me out if this is a common issue and if you have a solution for this? 
Thank you.

**Comment by Courela** [comment]
That's weird, I'm not getting any error at all, that package exists and is available [here](https://www.nuget.org/packages/NJsonSchema/10.4.1)

**Comment by aagarwallaMS** [comment]
Hey, thanks for the help. There was some issue with my org package source. I updated it and cleared the Nuget cache. This helped to restore the package properly.
