### ISSUE TITLE
How to create a dynamical field from the specific value of input.

### ISSUE THREAD

**Issue by walkerlin-msft** [WorkMaze/JUST.net#19]
Thanks for the great package.
For my special purpose, here is my expectation. Can I do that?

- Input.json
[
  {
    "ProductName": "xxxx",
    "Quantity": 1000
  }
]

Then,
- Output
[
 {
   "xxxx": 1000
 }
]

the "xxxx" can be anything from the input, for example. it could be "phone" or "laptop" or etc.
- Output (phone)
[
 {
   "phone": 1000
 }
]

Or,
- Output (laptop)
[
 {
   "phone": 1000
 }
]

Thanks for any suggestion.

**Comment by WorkMaze** [comment]
Hi,

I have added a new feature for dynamic properties. Please download the latest nuget. 

Consider the following input:-
```
{
  "Tree": {    
    "Branch": "leaf",
    "Flower": "Rose"
  }
}
```

Transformer:-
```
{
  "Result": {
      "#eval(#valueof($.Tree.Flower))": "x"
  }
}
```

Output:-
```
{  
   "Result":{  
      "Rose":"x"
   }
}
```

Kind Regards!
