### ISSUE TITLE
Check if a value is contained in an array present outside the current array looping block

### ISSUE THREAD

**Issue by aagarwallaMS** [WorkMaze/JUST.net#191]
Hello,

I am trying to implement a transformer in which I need to check if a value is present in an array. 
I want to add this check inside a looping block of another array. The input structure looks like this:
```
"Mapping": { 
    "Column1": [
      "val1"
    ],
    "Column2": [ "val1", "val3", "val4", "val5" ]
}
```
I want to convert it into something like this:
```
"NewMapping": [
  {
        "Columnname": "val1",
        "IsPresent": true
  },
 {
        "Columnname": "val3",
        "IsPresent": false
  }
 {
        "Columnname": "val4",
        "IsPresent": false
  }
 {
        "Columnname": "val5",
        "IsPresent": false
  }
]
```

Is there a way in which I can loop through the first array inside the loop of second array and check if the value is present?

Thank you.

**Comment by Courela** [comment]
This works, checking if the value exists through JsonPath (#valueof is always related to the root element):
```JSON
{
  "NewMappings": {
    "#loop($.Mappings.Column2)": {
      "Columnname": "#currentvalue()",
      "IsPresent": "#ifcondition(#valueof(#xconcat($.Mappings.Column1[?/(@ == ',#currentvalue(),'/)])),#currentvalue(),#toboolean(true),#toboolean(false))"
    }
  }
}
```

**Comment by aagarwallaMS** [comment]
Hey, thank you for the solution. 
There's one more level of complexity. What if the "Mapping" object is yet inside another loop? For example:
```
"Delta": {
    "Dataset": [
       "Mapping": { 
          "Column1": [
             "val1"
          ],
         "Column2": [ "val1", "val3", "val4", "val5" ]
       }
    ]
}
```
In this case, the #valueof function will have this as the parameter:
`#xconcat($.Delta.Dataset[##Current_Index_Of_Dataset##].Mapping.Column1[?/(@ == ',#currentvalue(),'/)])`

The transformer would look like this:
```
  "Delta": {
    "#loop($.Delta.Dataset)": {
      "Mapping": {
        "#loop($.Mapping.Column2)": {
          "ColumnName": "#currentvalue()",
          "IsPresent": "#ifcondition(#valueof(#xconcat($.Delta.Dataset[##Current_Index_Of_Dataset##].Mapping.Column1[?/(@ == ',#currentvalue(),'/)])),#currentvalue(),#toboolean(true),#toboolean(false))"
        }
      }
    }
  }
```

Is there a way in which I can extract the **##Current_Index_Of_Dataset##** value?

**Comment by Courela** [comment]
You can make an alias for '#loop($.Delta.Dataset)':
```JSON
{
  "Delta": {
    "#loop($.Delta.Dataset,aliasloop1)": {
      "Mapping": {
        "#loop($.Mapping.Column2)": {
          "ColumnName": "#currentvalue()",
          "IsPresent": "#ifcondition(#valueof(#xconcat($.Delta.Dataset[,#currentindex(aliasloop1),].Mapping.Column1[?/(@ == ',#currentvalue(),'/)])),#currentvalue(),#toboolean(true),#toboolean(false))"
        }
      }
    }
  }
}

**Comment by aagarwallaMS** [comment]
This worked! I was unaware that we could set alias for loops. 
Thank you so much for helping me out.
