### ISSUE TITLE
How do I covert string to boolean or string to integer in the transform?

### ISSUE THREAD

**Issue by anuradharajan** [WorkMaze/JUST.net#192]

**Comment by anuradharajan** [comment]
Also, I am using JUST.NETCore - version2.1.3. Does it have support for toboolean, tointeger??

**Comment by Courela** [comment]
That package was discontinued, [JUST.Net](https://www.nuget.org/packages/JUST.net/) is the way to go, it works on both .Net Framework and .Net Core and has the features that you want.
