### ISSUE TITLE
how do i check for empty json path value?

### ISSUE THREAD

**Issue by anuradharajan** [WorkMaze/JUST.net#196]
1. "val": if(some other json value is empty) set this value="a" else "b"
2. concat("some static string", #valueof(..))

this is not working
"#concat(test,#currentvalueatpath($.some path)"

**Comment by Courela** [comment]
You're right to use #concat since there's no way of comparing empty string, but using that it works.

Input:
```JSON
{
  "empty": "",
  "not_empty": "not empty"
}
```

Transformer:
```JSON
{
  "test_empty": "#ifcondition(#concat(test,#valueof($.empty)),test,is empty,not empty)",
  "test_not_empty": "#ifcondition(#concat(test,#valueof($.not_empty)),test,empty,is not empty)"
}
```

Result:
```JSON
{
  "test_empty": "is empty",
  "test_not_empty": "is not empty"
}
```

**Comment by anuradharajan** [comment]
I have another requirement to concatenate these 2 strings. i get a value null
#concat(/test,#valueof($.somepath))

is there a way to concat strings with / (forward slash) or escape them?
