### ISSUE TITLE
Concat

### ISSUE THREAD

**Issue by Rammun** [WorkMaze/JUST.net#2]
Hellow!

How can I concatenate a parameter with a constant value?
And how can I concatenate several parameters, more than two and with a separator?
```
{
	"Name": "Ivan",
	"Surname": "Ivanov",
	"Patronymic": "Ivanovich"
}
```
=>
```
{
	"FullName": "Ivanov Ivan Ivanovich"
}
```

Noticed strange behavior:
input
```
{
	"Name": "Ivan",
	"Surname": "Ivanov"
}
```
transform
```
{
	"FullName": "#concat(#valueof($.Name),#valueof($.Surname))"
}
```
output
```
{
	"FullName": "IvanIvanov"
}
```
but if transform
```
{
	"FullName": "#concat(#valueof($.Name), #valueof($.Surname))"
}
```
then output
```
{
	"FullName": "Ivan, #valueof($.Surname))"
}
```
Is it an error or should it be?

**Comment by WorkMaze** [comment]
Hello,

1. "FullName": "#concat(#valueof($.Name), #valueof($.Surname))" 

=> had a white space before #valueof($.Surname))" , that is why the strange results. However, now I am taking care of spaces and that should also give you the correct result.

2.  For Input

=> {
	"Name": "Ivan",
	"Surname": "Ivanov",
	"Patronomic": "Ivanovich"
}

if you want the Output
=>
{
	"FullName": "Ivanov Ivan Ivanovich"
}

The corresponding transformation is
=>
{
  "FullName": "#concat(#concat(#concat(#valueof($.Surname), ),#concat(#valueof($.Name), )),#valueof($.Patronomic))"
}

Explanation of the above 
Step 1. First we concat Ivanov with a whitespace.
Step 2. We concat Ivan with a whitespace.
Step 3. We concat the result from Steps 1 and 2.
Step 4. We concat resut from Step 3 with Ivanovich. 

These fixes are in the latest nuget 1.0.9.
Hope this helps!

**Comment by Rammun** [comment]
It works, thanks.

**Comment by WorkMaze** [comment]
Thanks for letting me know, closing the issue for now.
