### ISSUE TITLE
#valueof behaves as #currentvalueatpath

### ISSUE THREAD

**Issue by ostruk** [WorkMaze/JUST.net#20]
Hello and thank you for your awesome work!

I have JSON like this:

` {
     "prop": "hello",
     "arr": [
         {
             "title": "item1"
         },
         {
             "title": "item2"
         }
     ]
 }`

and would like to get this:

` {
     "list": [
         {
             "title": "item1",
             "prop": "hello"
         },
         {
             "title": "item2",
             "prop": "hello"
         }
     ]
 }`

I was hoping to use a transformer like this:

`
 {
     'list':
     {
         '#loop($.arr)':
         {
             'title': '#currentvalueatpath($.title)',
             'prop': '#valueof($.prop)'
         }
     }
 }`

But it seems "$" already refers to the root of the current iteration, and not the actual root of the document. So #valueof($.title) returns same thing as #currentvalueatpath($.title). I thought the purpose of #currentvalueatpath was to refer to the current iteration?

Is this intended? If so, any clues on how to achieve what I'm trying to do?

Thanks again!

**Comment by WorkMaze** [comment]
Hi,
Thanks for pointing it out. No it wasn't intended. `valueof` should be independent of loop and should not behave like `currentvalueatpath`.

I have published new Nuget package 5.1.1(2.1.1 for .NET Core) for this fix.

Regards!

**Comment by ostruk** [comment]
Thanks, so quick! Much appreciated!
