### ISSUE TITLE
Combining two arrays into one array of objects with values picked from each

### ISSUE THREAD

**Issue by danwale** [WorkMaze/JUST.net#201]
Hi,

I've got a JSON payload that has a **head** property, within that is a **fields** property that is an array describing a series of data fields (name of the field, the data type, the units and a few other attributes), at the same level as the **head** property is a **data** property that is an array with each object having two properties **time** which is a date time string and **vals** which is an array of values (one per field that was described in the **fields** property of the **head**).

**Sample Input**:
```
{
    "head": {
        "transaction": 0,
        "signature": 31705,
        "fields": [{
                "name": "Validation_Status",
                "type": "xsd:string",
                "process": "Smp",
                "settable": false,
                "string_len": 4
            }, {
                "name": "Sample_Point",
                "type": "xsd:string",
                "process": "Smp",
                "settable": false,
                "string_len": 12
            }, {
                "name": "RT",
                "type": "xsd:float",
                "units": "degC",
                "process": "Avg",
                "settable": false
            }
        ]
    },
    "data": [{
            "time": "2022-01-17T15:40:00",
            "vals": ["raw", "FIAQRT003", 27.75]
        }
    ]
}
```

What I'd like to get to is having an output that combines the field name, the value and the timestamp so we get an array of objects representing the data.

**Desired Output**:
```
{
    "channel_data": [
       {
           "name": "Validation_Status"
           "value": "raw",
           "time": "2022-01-17T15:40:00"
       },
       {
           "name": "Sample_Point"
           "value": "FIAQRT003",
           "time": "2022-01-17T15:40:00"
       },
       {
           "name": "RT"
           "value": "27.75",
           "time": "2022-01-17T15:40:00"
       }
    ]
}
```
I don't mind if the values are all strings, I have a process that will interpret those correctly further along the line but I'm not sure if I can get these two arrays combined together using existing functionality in the library or if I need to write an extension function.

Plus handling the fact it seems like the vendors device that is sending this input JSON may send through multiple sets of values in the **data** array with varying timestamps so I should be iterating through those and pulling out the values for each date time. They haven't provided such a sample yet with more than one timestamp but it's the only reason I can see for them using this structure.

Thanks in advance.

**Comment by Courela** [comment]
This will work if data has only one element, if it has more probably the loop must be done in it.

```JSON
{
  "channel_data": {
    "#loop($.head.fields)": {
      "name": "#currentvalueatpath($.name)",
      "value": "#valueof(#xconcat($.data[0].vals[,#currentindex(),]))",
      "time": "#valueof($.data[0].time)"
    }
  }
}
```

**Comment by danwale** [comment]
Thanks for that, yes that will handle that basic scenario of only one data element, much appreciated.

I think the other may be a bit too complex for me to work out, I've had a few attempts at it and nothing seems to get me the right output because of the array vals within the data element.

**Comment by Courela** [comment]
Does head/fields array has only one element or there may be more?

**Comment by danwale** [comment]
There is always one fields array in the head with 1 or more elements describing the fields. Then one or more elements in the data array, the fields should align in a one to one relationship with the values in the vals array of each data element.

The data is coming from an IoT device that pushes telemetry data, so far in testing I've only seen the data array have one element but the vendor has confirmed with me that it could have multiple elements with individual timestamps.

**Comment by Courela** [comment]
This is the closest that I can think of, iterating over data array and then over vals array. Since there are two loops, it creates arrays as elements of channel_data array.

Input:
```JSON
{
	"head": {
		"transaction": 0,
		"signature": 31705,
		"fields": [
			{
				"name": "Validation_Status",
				"type": "xsd:string",
				"process": "Smp",
				"settable": false,
				"string_len": 4
			},
			{
				"name": "Sample_Point",
				"type": "xsd:string",
				"process": "Smp",
				"settable": false,
				"string_len": 12
			},
			{
				"name": "RT",
				"type": "xsd:float",
				"units": "degC",
				"process": "Avg",
				"settable": false
			}
		]
	},
	"data": [
		{
			"time": "1999-02-09T04:10:02",
			"vals": [
				"dummy",
				"TEST_DUMMY",
				99.99
			]
		},
		{
			"time": "2022-01-17T15:40:00",
			"vals": [
				"raw",
				"FIAQRT003",
				27.75
			]
		}
	]
}
```

Transformer:
```JSON
{
	"channel_data": {
		"#loop($.data,data)": {
			"#loop($.vals)": {
				"name": "#valueof(#xconcat($.head.fields[,#currentindex(),].name))",
				"value": "#currentvalue()",
				"time": "#currentvalueatpath($.time,data)"
			}
		}
	}
}
```

Output:
```JSON
{
	"channel_data": [
		[
			{
				"name": "Validation_Status",
				"value": "dummy",
				"time": "1999-02-09T04:10:02"
			},
			{
				"name": "Sample_Point",
				"value": "TEST_DUMMY",
				"time": "1999-02-09T04:10:02"
			},
			{
				"name": "RT",
				"value": 99.99,
				"time": "1999-02-09T04:10:02"
			}
		],
		[
			{
				"name": "Validation_Status",
				"value": "raw",
				"time": "2022-01-17T15:40:00"
			},
			{
				"name": "Sample_Point",
				"value": "FIAQRT003",
				"time": "2022-01-17T15:40:00"
			},
			{
				"name": "RT",
				"value": 27.75,
				"time": "2022-01-17T15:40:00"
			}
		]
	]
}
```

**Comment by danwale** [comment]
Thank you so much, I hadn't quite got it that close but had noticed the array was an element within an array in my closest attempt. 

I might make a tweak to the service that consumes the channel_data to detect that condition and handle it automatically.

**Comment by Courela** [comment]
Maybe with an 'applyover' one can make a single array out of that multiple array.

**Comment by jingkunhub** [comment]
Hi Courela,
In the above transformation, the name value will be null if removing #xconcat. I'm trying to use #currentindex() directly. It doesn't work either. Basically I have a similar use case of getting a value from an array outside with the same index of the #loop.

Thanks,
Jingkun

**Comment by Courela** [comment]
#xconcat will create json path used in #valueof. The loop refers to 'data' property, so to fetch a value from outside the loop, one must use #valueof with an absolute path. #xconcat can't be removed if one wants to use values from loop element.
#valueof will look into whole input, not loop element, it needs an absolute path.
