### ISSUE TITLE
Transformation for JSON properties that can be both a JSON array or a JSON object

### ISSUE THREAD

**Issue by sertanyaman** [WorkMaze/JUST.net#206]
Hi;
We need to transform a JSON response from a third party API that returns its properties varyingly as objects if there is only one iteration and arrays if there are multiple iterations in them... I use #loop but it only works if the result is more than one row so it is an array.. and gives an error if it returns only one row as an object.. How to overcome this problem?

Example faulty input :

`{
   "SHIPMENTENTITY": {
      "SHIPMENTID": "USMF-000006"
}
}`

transformer :

`{ "#loop($.SHIPMENTENTITY)" : 
{
    "reference": "#currentvalueatpath($.SHIPMENTID)"
}
}`

Error:

`JSON transformation error: Can not add property reference to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.`

Example response from the same API which works :

`{
		"SHIPMENTENTITY": [
			{
				"SHIPMENTID": "USMF-000003"
			},
			{
				"SHIPMENTID": "USMF-000006"
			}
		]
}`

**Comment by Courela** [comment]
This works:
```JSON
{
  "#ifgroup(#exists($.SHIPMENTENTITY.SHIPMENTID))": { 
    "reference": "#valueof($.SHIPMENTENTITY.SHIPMENTID)" 
  },
  "#ifgroup(#exists($.SHIPMENTENTITY[0]))": {
    "result": {
      "#loop($.SHIPMENTENTITY)" : {
        "reference": "#currentvalueatpath($.SHIPMENTID)"
      }
    }
  }
}
```

I don't know if this is a problem, or if one can had a "result" property also in the first #ifgroup, but the result of #loop in the second #ifgroup requires a parent property to work, hence the "result" property.
