### ISSUE TITLE
MIT license? Dependencies on GPL based libraries

### ISSUE THREAD

**Issue by JMayrbaeurl** [WorkMaze/JUST.net#21]
Hi,

Since you're including Newtonsoft Json.Schema library, that's only available under GPL or commercial license, I don't think that you can use the MIT license. Or do I miss something here?

Juergen

**Comment by WorkMaze** [comment]
Hi,

I am just referencing the library and not modifying the code base of Newtonsoft Json.Schema. I think I can use the MIT license here. Please let me know otherwise.

regards!

**Comment by bc110402922** [comment]
Hi, can i use PPMP C# implementation for commercial use?
