### ISSUE TITLE
SumAtPath on fractions

### ISSUE THREAD

**Issue by olafloogman** [WorkMaze/JUST.net#22]
Hi, it seems that the'sumathpath' function only operates on numbers and not on fractions. Are there any plans to support fractions in the future?

**Comment by WorkMaze** [comment]
Hi, 
Please download the latest nuget 5.1.3 (2.1.3 for .NET Core).
'sumatpath' should now work for floating values (eg. 60.5, 10.2 etc.). 
Is that what you meant? or did you mean fractions written in the form (5/6 , 1/10 etc.)?

**Comment by olafloogman** [comment]
That's great news, thanks very much! Yes I was referring to floating values indeed.
