### ISSUE TITLE
Array filtering not workin with integer number comparison

### ISSUE THREAD

**Issue by mdeymidwinter** [WorkMaze/JUST.net#231]
I need to filter an array based on some values. It works for string comparison but not integer comparison. How should we do the integer value comparison

Working string value comparison
"#loop(allocations[?(@.fundName != 'Conservative (Super)')])"

Does not work
"#loop(allocations[?(@.percentage != '0')])"
"#loop(allocations[?(@.percentage != 0)])"

ex data:
allocations":[{"fundId":40000037,"fundName":"Conservative (Super)","percentage":49.9980000799968},{"fundId":40000038,"fundName":"Balanced (Super)","percentage":29.99880004799808}]

**Comment by Courela** [comment]
It's working fine here, which version do you use?

**Comment by mdeymidwinter** [comment]
Thank you for letting me know. It is an older version 4.0.2.

**Comment by mdeymidwinter** [comment]
We are using JmesPathSelectable and for this the syntax for the number comparison should have been. I was missing the `

"#loop(allocations[?(@.percentage != `0`)])"
