### ISSUE TITLE
nested loops

### ISSUE THREAD

**Issue by anuradharajan** [WorkMaze/JUST.net#232]
Could you provide a transform for this??

Input.json
{
  "Systems": [
    {
      "Id": "SystemId1",
      "Components": [
        {
          "Id": "CompId1"
        },
        {
          "Id": "CompId2"
        }
      ]
    },
    {
      "Id": "SystemId2",
      "Components": [
        {
          "Id": "CompId3"
        },
        {
          "Id": "CompId4"
        }
      ]
    }
  ]
}

ExpectedOutput.json
{
  "SystemsAndComponents": [
    {
      "Id": "SystemId1"
    },
    {
      "Id": "CompId1"
    },
    {
      "Id": "CompId2"
    },
    {
      "Id": "SystemId2"
    },
    {
      "Id": "CompId3"
    },
    {
      "Id": "CompId4"
    }
  ]
}

**Comment by Courela** [comment]
Each loop returns an array, so in order to return only one array, one needs to concatenate them. This only can be done with two tranformations, so using #applyover will do the trick.

```JSON
{
  "SystemsAndComponets": "#applyover({ 'Systems': { '#loop($.Systems)': { 'Id': '#currentvalueatpath($.Id)' } }/, 'Components': { '#loop($.Systems[:].Components[:])': { 'Id': '#currentvalueatpath($.Id)' } },'#concat(#valueof($.Systems),#valueof($.Components))')" 
}
```

**Comment by anuradharajan** [comment]
On this loop -> #loop($.Systems[:].Components[:] -> is there a way to get current index of the outer System loop? #currentindex() gives me the index of the inner loop (Components)

**Comment by Courela** [comment]
That is looping over items chosen by JsonPath, for JUST is just one loop. Maybe there's a way to fetch the index of Systems' elements, although I'm not seeing one at the time.

**Comment by anuradharajan** [comment]
> That is looping over items chosen by JsonPath, for JUST is just one loop. Maybe there's a way to fetch the index of Systems' elements, although I'm not seeing one at the time.

Is there another way to do this? transform an inner loop content but have access to outer loop properties and index, still end up with 1 array as the output

**Comment by Courela** [comment]
Access the outer loop can be accomplished making an alias for each loop, but each each loop returns an array, so you end up having 2 arrays.

**Comment by Courela** [comment]
Yes
[https://github.com/WorkMaze/JUST.net#-nested-array-looping](https://github.com/WorkMaze/JUST.net#-nested-array-looping)

**Comment by Courela** [comment]
Every function described [here](https://github.com/WorkMaze/JUST.net#-array-looping) can have an alias as an extra parameter, so the function could relate to that loop. Even #loop function can have an alias referring to a specific loop.

```JSON
#loop($.Systems,systems) {
  #loop($.dummy) {
    ...
    #loop($.Components,comp,systems) {
      "System_index": "#currentindex(systems)"
    }
    ...
  }
}
```

**Comment by anuradharajan** [comment]
Thanks! one final question on loops - 
Is there a way to access outer loop properties from inside a loop?

Input
{
"Outer": {
"rootProp: "val1",
"Innerloop" : [
{ "loopProp": "val3" },
{ "loopProp": "val4" },
]
}
}

Output
{
"Response": {
"Loop" : [
{ "loopProp: "val3", "rootProp: "val1" },
{ "loopProp: "val4", "rootProp: "val1"},
]
}
}
How do we access the outer rootProp value when inside a loop

**Comment by anuradharajan** [comment]
All set!
