### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by ZipZamZappem** [WorkMaze/JUST.net#24]
Where is the source code for this component? Extremely interested in seeing this. Where can you get it?

**Comment by WorkMaze** [comment]
The source code is going to be made available soon. I will update this issue.

**Comment by ZipZamZappem** [comment]
Thank you so much! (It was never my intention to insult you. I greatly appreciate your efforts!)

And Congratulations on your more important job! (My brother once told me that people often mistakenly say, “I have kids.” No! Kids have you!)

Thanks, Charles C. Poston

**Comment by WorkMaze** [comment]
Source code available now.
