### ISSUE TITLE
Filtering Array Help Needed

### ISSUE THREAD

**Issue by seanarmstrong87** [WorkMaze/JUST.net#243]
Hi. I have an input json like below, containing an array of objects called `data`, confusingly each object also has a `data` property as well as `meta`:

```{
  "paging": {
    "totalItems": 76,
    "totalPages": 16,
    "pageSize": 5,
    "currentPage": 1,
    "maxPageSize": 250
  },
  "data": [
    {
      "data": {
        "uniqueId": "cz-vehicle-17336428",
        "name": "ŠKODA SUPERB NFD7FD7GC* ACDTUAX01 3T",
        ...
      },
      "meta": {

        "createdAt": "2022-07-01T21:16:50.1252598+00:00",
        "hash": "bc53b2682f8498abffc49c3203609911da334d6d3ad9f8156a7c0499fc83caf7",
      }
    },
    {
      "data": {
        "uniqueId": "cz-vehicle-17168912",
        "name": "HYUNDAI I 30 M6DAZ11 F5P91 PDE",
        ...
      },
      "meta": {
        "createdAt": "2022-07-01T21:16:50.1252598+00:00",
        "hash": "6b5a1953d45a35341385575eead2468f115633e507da8f84a538a74b877d0c1a",
      }
    },
    ...
  ]
}
```

I want to use the bulk operations to copy the whole json but remove some properties from each (inner) data object in the array. (The same property from each item) i.e. `name`. 

Is this possible using bulk operations? 

I can't workout how to pass the path of the properties of the items in the data array (outer data property) that I want to remove to the `#delete()` method.

I don't want to have to re-construct each object in the array. I have not shown it here but there are many other nested properties and it can change so that is not an option.

I hope that makes sense.

Sean

Edit: This is the closest I have come: `{"#": ["#copy($)", "#delete($.data[*].data.name)"]}` but it throws an exception because the selector returns multiple tokens. If I specify only one item in the array with an index (i.e. 0) it works for that one item.

**Comment by Courela** [comment]
I was able to select the property that you want, same as you accomplished but with other JsonPath (#delete($.data..data.name)), but #delete doesn't seem to work here... #delete expectes a token that is present in the input not a selection.
I'll try another approach, to see if it works.

**Comment by seanarmstrong87** [comment]
Ah I didn't realise it was possible to split the use of bulk functions like that.

Thanks a lot for investigating, I will try it out.
