### ISSUE TITLE
Loop through an array and retrieve value of another array on some condition

### ISSUE THREAD

**Issue by yonaeisenberg** [WorkMaze/JUST.net#245]
Hi I am trying to loop through an array and put on one of the fields the value from another array on conditional ID. I suppose if some ID exists in the first array a corresponding object with the same id also exists in the second array.

I try to retreive the object from second array using valueof and conditional [?@.id==]

[input_example.txt](https://github.com/WorkMaze/JUST.net/files/9175819/input_example.txt)
[transformer_example.txt](https://github.com/WorkMaze/JUST.net/files/9175821/transformer_example.txt)
[desired_output_example.txt](https://github.com/WorkMaze/JUST.net/files/9175822/desired_output_example.txt)
[received_output_example.txt](https://github.com/WorkMaze/JUST.net/files/9175820/received_output_example.txt)

if I put a hardcoded id to the right of the  [?@.id== 2] then it works. But I can't access in the comparison the id of the current userID in the first array, which is what I try to do.

Appreciate your help, thanks!

**Comment by yonaeisenberg** [comment]
I added user_test to see if the I manage to get the velue of the id there, and it works

**Comment by Courela** [comment]
JUST functions can't be embbeded in a static expression, they must be called at start of a parameter. You can't do this:
```JSON
"user": "#valueof($.otherObject.otherArray[?(@.id==#currentvalueatpath($.user.userId))])"
```

What must be done is use the #concat/#xconcat functions to build a dynamic JsonPath expression:
```JSON
"#valueof(#xconcat($.otherObject.otherArray[?/(@.id==,#currentvalueatpath($.user.userId),/)]))"
```

The expression has parenthesis, so they need to be escaped, since they are reserved characters.

**Comment by yonaeisenberg** [comment]
Hi
Your solution did not work
'Error while calling function : #valueof(#xconcat($.otherObject.otherArrays[?/(@.id==,#currentvalueatpath($.user.userId),/)])) 

Important precision: I am using JUST for .Net 4.7.2 , not for .Net Core

**Comment by Courela** [comment]
[JUST.Net](https://www.nuget.org/packages/JUST.net/) works for both, that's the package that has been maintained.

**Comment by yonaeisenberg** [comment]
When I try to install JUST.net from Nuget packages I get the following error:

Error		Could not install package 'JUST.net 4.2.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by yonaeisenberg** [comment]
On the other hand I see another nuget JUST with the following description:

**Comment by yonaeisenberg** [comment]
It is okay I installed 4.2.0 instead of 4.2.1 and it works!! Thanks a lot
