### ISSUE TITLE
Set dynamic Propertyname 

### ISSUE THREAD

**Issue by Shelli18** [WorkMaze/JUST.net#246]
270 / 5.000
Übersetzungsergebnisse
Hello, is it possible to set the property name dynamically? Or is something planned:

Example:
  "attributes":
         {
           "#loop($.Attributes)": {
             "#currentvalueatpath($.ExternalId)": "#currentvalueatpath($.Value)"
           }
         }

here it unfortunately returns "#currentvalueatpath($.ExternalId)" as the property name

thx

**Comment by Courela** [comment]
Use #eval, it will create a dynamic property as you want:
```JSON
{
  "attributes": {
    "#loop($.Attributes)": {
      "#eval(#currentvalueatpath($.ExternalId))": "#currentvalueatpath($.Value)"
    }
  }
}
```

**Comment by Shelli18** [comment]
Perfect, exactly what I was looking for and works. Thank you for the fast answer
