### ISSUE TITLE
Operators in if-condition method

### ISSUE THREAD

**Issue by daniloavilez** [WorkMaze/JUST.net#25]
Hi,

I was try to use `if-condition` method with some operators like (<,>,>=,<=).

Is it possible to use with `if-condition`?

`"{ 'has_items' : '#ifcondition(#valueof($.items[0].answers[?(@.number == 3 && @.type == 'number')].number),3,yes,no)' }"`

Above, what I have tried. Thanks!

**Comment by WorkMaze** [comment]
Hi,

At the moment operators are not supported.I will add operators in my next release which will evaluate to true\false.

Kind regards!

**Comment by rskumargithub** [comment]
Hi, am still not getting filtered if I used operators in ifCondition. can you help me with the same example ? 
"{ 'has_items' : '#ifcondition(#valueof($.items[0].answers[?(@.number == 3 && @.type == 'number')].number),3,yes,no)' }
