### ISSUE TITLE
JsonPath in Array question

### ISSUE THREAD

**Issue by ZipZamZappem** [WorkMaze/JUST.net#26]
I have this:
{
	"Array": [
		{
			"Dog": "Fido",
			"Treat": "Chewbone"
		}
	]
}

And this fails:
{ "Dog Pound": { "#loop($.Array)": "#currentvalueatpath($.Dog)" } }

I want this:

{ "Dog Pound": [ "Fido" ] }

Is there something wrong with my JsonPath? When I test it against a JsonPath tool, the path $.Array[*].Dog gets the value. So current value should be just $.Dog shouldn't it?

**Comment by WorkMaze** [comment]
Hi,

currentvalueatpath can only be used on RHS (value) and not as a property name.

This transformation will work:
`{
  "Dog Pound": {
    "#loop($.Array)": {
      "CurrentValue": "#currentvalueatpath($.Dog)"
    }
  }
}`

**Comment by ZipZamZappem** [comment]
Yes I get that (would have to use eval() for that, right?) but I just want a bare array like this:

{ 
    "Dog Pound": [ "Fido"  ]  // ...and so on if I had more anonymous 'Dog-Treat' array elements defined
} 

I want to just pull the attribute value out as just an array element. Given the referenced structure then how would I do that?

**Comment by WorkMaze** [comment]
Hi,

For this case the following transformation should work.

`{
  "Dog Pound": {
    "#loop($.Array)": "#currentvalueatpath($.Dog)"
  }
}`

But, looks like there is a bug I need to fix.

**Comment by ZipZamZappem** [comment]
Thanks – I’m in no hurry. (Just excited that I understood it enough to get the correct syntax.) I’m not in production just happy I found a tool that will allow me to avoid DLL hell.

**Comment by WorkMaze** [comment]
Hi, the bug has been fixed in the new .NET Standard nuget package.
