### ISSUE TITLE
Is there a way to pass multiple input json during transformation?

### ISSUE THREAD

**Issue by joshidp** [WorkMaze/JUST.net#268]
Hello,

Is there a way to pass multiple input json during transformation

In Transform method we have only one input json option, in my requirement I have two different json using which I need to do a transformation, any workaround please?

Thanks

**Comment by Courela** [comment]
You mean having a transformation with more than one input, paths can be from any of the inputs?
If so, there isn't, the best option is to combine the inputs into one and apply a transformation over it.
