### ISSUE TITLE
Allow registration of custom functions for usability

### ISSUE THREAD

**Issue by NicolaiPetri** [WorkMaze/JUST.net#29]
Hi,
It would be very nice if it was possible to somehow "register" a dll with custom functions so they could be used like any built in function .. preferably like #myns::myfunc() syntax where myns is a custom namespace specified when registering dll/class.

I hope this makes sense ?

Thanks for a nice piece of software.
---
Nicolai

**Comment by Courela** [comment]
That could be handy, I will have a go on this one

**Comment by WorkMaze** [comment]
Hi @Courela , Thank you for your contribution towards this library. Yes please, if you would like to have a go at this, I would appreciate it.

**Comment by WorkMaze** [comment]
Changes are reflected in new nuget 2.0.0.
