### ISSUE TITLE
#concat

### ISSUE THREAD

**Issue by Rammun** [WorkMaze/JUST.net#3]
Hi!

And this again I)

Is it possible to implement a concat method as #concat(#valueof(...),#const(...)) or  #concat(#const(...),#valueof(...))?
In the current version impossible to make a concatenation with ','.
And would like to have a method #concat(#const([separator]),#valueof(...),#valueof(...),...), because join several fields looks as
"Document": "#concat(#concat(#concat(#concat(#concat(#concat(#valueof($.Citizenship), ; ),#valueof($.DocType)), ; ),#valueof($.DocNumber)), ; ),#valueof($.DocumentAdditionalInfo))"
And it is not the biggest line)

**Comment by WorkMaze** [comment]
Hi,

Please have a look at "Multiple argument & constant functions" in README.

These features are in latest nuget 1.0.10.

Hope this solves your case!

**Comment by Rammun** [comment]
Hi,

Thank you very much for resolving the problem.
But there is remaining of a difficulty to concatenate fields with a custom separator.

the input
{
	"Citizenship": "DE",
	"DocType": "pasport",
	"DocNumber": "BC599500",
}
=>
the output
{
	"Document": "citizenship: DE; type: pasport; number: BC599500"
}

for example the transform
{
	"Document": "#xconcat(#concat(#str(citizenship: ),#valueof($.Citizenship)),#str(; ),#concat(#str(type: ),#valueof($.DocType)),#str(; ),#concat(#str(number: ),#valueof($.DocNumber)))"
}

**Comment by WorkMaze** [comment]
Hi,
The only problem was with comma(,) since it is a reserved keyword. Custom separators can be used as constant strings.

The following transformation will produce your desired output:-

``{
  "Document": "#xconcat(citizenship: ,#valueof($.Citizenship),; ,type: ,#valueof($.DocType),; ,number: ,#valueof($.DocNumber))"
}``

Hope this helps!
Regards.
