### ISSUE TITLE
#ifcondition possible isue

### ISSUE THREAD

**Issue by ericartman** [WorkMaze/JUST.net#30]
To whom it may concern,
given the following JSON:
`{
    "total": 3,
    "data": [
        {
            "PlacementId": 1,
            "candidate": {
                "CandidateId": 2311,
                "secondaryOwners": null,
                "owner": null,
                "id": 2311,
                "CustomUserId": 0
            },
            "approvingClientContact": null,
            "owner": {
                "id": 1949,
                "OwnerId": 1949
            },
            "CustomUserId": 42
        },
        {
            "PlacementId": 1,
            "candidate": {
                "CandidateId": 2311,
                "secondaryOwners": null,
                "owner": null,
                "id": 2311,
                "CustomUserId": 0
            },
            "approvingClientContact": null,
            "owner": {
                "id": null,
                "OwnerId": null
            },
            "CustomUserId": 42
        },
        {
            "PlacementId": 1,
            "candidate": {
                "CandidateId": 2311,
                "secondaryOwners": null,
                "owner": null,
                "id": 2311,
                "CustomUserId": 0
            },
            "approvingClientContact": null,
            "owner": null,
            "CustomUserId": 42
        }
    ]
}`
and the following transformation:
` "Placement": {
    "data": {
      "#loop($.data)": {
        "CustomUserId": "#valueof($.CustomUserId)",
        "candidate": {
          "CandidateId": "#valueof($.candidate.CandidateId)"
        },
        "clientCorporation": {
          "ClientCorporationId": "#valueof($.clientCorporation.ClientCorporationId)"
        },
        "owner": {
          "OwnerId": "#ifcondition(#valueof($.owner),null,#valueof($.CustomUserId),#ifcondition(#valueof($.owner.OwnerId),null,#valueof($.CustomUserId),#valueof($.owner.OwnerId)))"
        }
      }
    }
}`

I get a null reference exception in the transformer. I cannot figure out the possible cause as the _#ifcondition_ nesting seems to be fine. I have tried using _#valueof(null)_ as the evaluation expression instead of just _null_ but that did not seem to help. It generally evaluates to false of the owner is null.

If I use _null_ the #_ifcondition_ evaluates to false, but if I use _#valueof(null)_ - I get an error, with the following transfomer:
`#valueof($.owner),null,#valueof($.CustomUserId),#valueof($.owner.OwnerId)`

Additional question - is there a way of accessing a variable from a "higher level" in the loop section? e.g. if "CustomUserId" was at the same level as "data".

**Comment by Courela** [comment]
My guess is that you're using #valueof instead of #currentvalueatpath to try to get values from the iterated object.

About the additional question, I would say that what you are doing to get the value of CustomUserId inside the iterated object is what you would do if the CustomUserId was at the same level as data.

**Comment by Courela** [comment]
`{
	"Placement": {
		"data": {
			"#loop($.data)": {
				"CustomUserId": "#currentvalueatpath($.CustomUserId)",
				"candidate": {
					"CandidateId": "#currentvalueatpath($.candidate.CandidateId)"
				},
				"clientCorporation": {
					"ClientCorporationId": "#currentvalueatpath($.clientCorporation.ClientCorporationId)"
				},
				"owner": {
					"OwnerId": "#ifcondition(#existsandnotempty($.owner.OwnerId),true,#currentvalueatpath($.owner.OwnerId),#currentvalueatpath($.CustomUserId))"
				}
			}
		}
	}
}`

**Comment by Courela** [comment]
I think this is what you want:

`{
	"Placement": {
		"data": {
			"#loop($.data)": {
				"CustomUserId": "#currentvalueatpath($.CustomUserId)",
				"candidate": {
					"CandidateId": "#currentvalueatpath($.candidate.CandidateId)"
				},
				"clientCorporation": {
					"ClientCorporationId": "#currentvalueatpath($.clientCorporation.ClientCorporationId)"
				},
				"owner": {
					"OwnerId": "#ifcondition(#existsandnotempty($.owner.OwnerId),true,#currentvalueatpath($.owner.OwnerId),#currentvalueatpath($.CustomUserId))"
				}
			}
		}
	}
}`

**Comment by WorkMaze** [comment]
This issue is fixed by @Courela
