### ISSUE TITLE
Request for Nested array looping example with DataTransformer (JSON to XML) / Missing feature or possible bug

### ISSUE THREAD

**Issue by PeterBridge** [WorkMaze/JUST.net#304]
**Context**
After checking the examples and UT, I noticed that there is just an example of "Nested array looping" for JSON to JSON which uses JsonTransformer().Transform(transformer, input).

There is also one for JSON to XML which uses DataTransformer().Transform(transformer, input). But this one doesn't have "Nested array looping"

**Issue**
After many tries to convert JSON to XML with "Nested array looping" I keep getting exceptions or unexpected results.

it is possible that "Nested array looping" is only supported in JsonTransformer but not in DataTransformer.

If not a missing feature or bug, it would be very helpful to add an example of "Nested array looping" for DataTransformer (JSON to XML)

**Version used**
JUST.net 4.4.1

**Comment by Courela** [comment]
DataTransformer has not been updated as JsonTransformer was. They share some code, some features may also work with DataTransformer, but it's not guaranteed.

If you post an example of what you are trying to achieve, I can take a look to see if it's an easy fix or not.

**Comment by PeterBridge** [comment]
Thanks. Just anything with nested arrays to XML. Here an example:
**Input**
`{
  "employee": [
    {
      "name": "jim",
      "details": [
        {
          "id": "detNum1",
          "countries": [
            {
              "short": "mex",
              "lang": "es"
            },
            {
              "short": "usa",
              "lang": "en"
            }
          ]
        }
      ],
      "notes": [
        "note a",
        "note b",
        "note c"
      ]
    },
    {
      "name": "karl",
      "details": [
        {
          "id": "detNum2"
        }
      ]
    }
  ],
  "notes": [
    "note 1",
    "note 2"
  ]
}
`

**Expected output**
<employee>
  <name>jim</name>
  <details>
    <id>detNum1</id>
    <countries>
      <country>
        <short>mex</short>
        <lang>es</lang>
      </country>
      <country>
        <short>usa</short>
        <lang>en</lang>
      </country>
    </countries>
  </details>
  <notes>note a</notes>
  <notes>note b</notes>
  <notes>note c</notes>
</employee>
<employee>
  <name>karl</name>
  <details>
    <id>detNum2</id>
  </details>
  <notes>note 1</notes>
  <notes>note 2</notes>
</employee>


**Attachment**
Looks like code preview doesn't work for XML so also adding here the example files
[Example.zip](https://github.com/user-attachments/files/16326656/Example.zip)

**Comment by PeterBridge** [comment]
Found the solution, it can be done using loopwithincontext, somethign like this:
"#loop($.parentNode)": {
	"#loopwithincontext($.subNode)":	{
		//code
	}
}
Thanks!
