### ISSUE TITLE
Is it possible to flatten/transform this json input to this result with JUST?

### ISSUE THREAD

**Issue by OlkDer** [WorkMaze/JUST.net#32]
Json input:
```
[
  {
    "target": "target1",
    "datapoints": [
      [
        "datapoint1_target1_x",
        "datapoint1_target1_y",
      ],
      [
        "datapoint2_target1_x",
        "datapoint2_target1_y",
      ],
    ]
  },
  {
    "target": "target2",
    "datapoints": [
      [
        "datapoint1_target2_x",
        "datapoint1_target2_y",
      ],
      [
        "datapoint2_target2_x",
        "datapoint2_target2_y",
      ],
    ]
  }
]
```
And want to flatten/transform this to following structure:
```

[
  {
    "target": "target1",
    "x": "datapoint1_target1_x",
    "y": "datapoint1_target1_y",
  },
  {
    "target": "target1",
    "x": "datapoint2_target1_x",
    "y": "datapoint2_target1_y",
  },
  {
    "target": "target2",
    "x": "datapoint1_target2_x",
    "y": "datapoint1_target2_y",
  },
  {
    "target": "target2",
    "x": "datapoint2_target2_x",
    "y": "datapoint2_target2_y",
  },
 ]
```
Thanks a lot

**Comment by Courela** [comment]
Seems that it can't handle arrays inside an array. If you can wrap the inside arrays in an object then it is possible. Also the root of the input must be an object also, not an array.

The input should look like this:
`{
	"arr": [{
			"target": "target1",
			"datapoints": [{
					"wrapperField":
					[
						"datapoint1_target1_x",
						"datapoint1_target1_y"
					]
				}, {
					"wrapperField": [
						"datapoint2_target1_x",
						"datapoint2_target1_y"
					]
				}
			]
		}
	]
}
`

**Comment by WorkMaze** [comment]
Refer to issue #37.
