### ISSUE TITLE
Support for Array as JSON

### ISSUE THREAD

**Issue by Carbammato** [WorkMaze/JUST.net#36]
Hello, everyone. I'm writing this to ask if there's a way to pass, as a Transformer, an Array as JSON.

As example, this is what I have:
```
{
     "first": [
			{
				"sign-name": "Heart rate",
				"date": "2018-12-01",
				"value": 72
			},
			{
				"sign-name": "Heart rate",
				"date": "2018-12-03",
				"value": 65
			},
			{
				"sign-name": "Heart rate",
				"date": "2018-12-04",
				"value": 75
			},
		],
     "second": [
			{
				"sign-name": "Heart rate",
				"date": "2018-12-01",
				"value": 70
			},
			{
				"sign-name": "Heart rate",
				"date": "2018-12-03",
				"value": 55
			},
			{
				"sign-name": "Heart rate",
				"date": "2018-12-04",
				"value": 68
			},
		]
}
```

And my transformer would be something like this:
```
[{
    "title": "#valueof($.first[0].sign-name)",
    "uom": "bpm/min",
    "xLabel": "#valueof($.first[0].sign-name)",
    "yLabel": "bpm/min",
    "data": {
        "#loop($.first)": {
            "x": "#currentvalueatpath($.date)",
            "y": "#currentvalueatpath($.value)"
        }
    }
}, {
    "title": "#valueof($.second[0].sign-name)",
    "uom": "bpm/min",
    "xLabel": "#valueof($.second[0].sign-name)",
    "yLabel": "bpm/min",
    "data": {
        "#loop($.second)": {
            "x": "#currentvalueatpath($.date)",
            "y": "#currentvalueatpath($.value)"
        }
    }
}]
```

Unfortunately, this won't work because of an error:
```
Error during JUST transformation
Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: StartArray. Path '', line 1, position 1.
```

Am I doing something wrong? Or is it simply something I can't do? I thank you all in advance for any help you can give me.

**Comment by Carbammato** [comment]
Sorry, this was a duplicate of #32 .

**Comment by Carbammato** [comment]
Sorry, I'm making some confusion. I was reading #32 , and I'm noticing I'm having a very similar issue. 

So, just to be clear (then I'll fade away, I promise), I wish to ask if there's any support for Array as a Transformer, instead of have to create a proper JSON with property containing the array.

**Comment by Courela** [comment]
AFAIK the transformer must be an object. Probably it won't be hard to support an array, as doing a transformation for each element of the array.
That's what you could also do by yourself, just iterate through the transformation array and apply each transformation, then join all the results in an array.

**Comment by Carbammato** [comment]
Thank you for your answer, Courela.

> AFAIK the transformer must be an object. Probably it won't be hard to support an array, as doing a transformation for each element of the array.

That is what I was afraid of. I wonder if it really that simple as you hope and, if so, if there's any plan to support it in the near future. (I wish I had the time to put my hands on code to study it and understand it by myself)

> That's what you could also do by yourself, just iterate through the transformation array and apply each transformation, then join all the results in an array.

That could be a bit difficult, since I'm using JUST as part of a more complex method and I need to refactor a lot. I prefer (as maybe was you to suggest in the previously quoted issue) to put everything inside a variable.

**Comment by Courela** [comment]
I can have a look at it, but probably only on the weekend.

**Comment by Carbammato** [comment]
A lot of thanks to you, @Courela . Your effort to this project is really appreciated. Thanks again!

**Comment by WorkMaze** [comment]
Thanks @Courela. Your efforts are appreciated. New Nuget version 2.0.1 has been released.
