### ISSUE TITLE
custom function syntax

### ISSUE THREAD

**Issue by yvz5** [WorkMaze/JUST.net#38]
custom function syntax is really ugly. I am building an editor kinda thing and have a couple of custom functions. 
instead of this long syntax
`#customfunction(JUST.NET.Test,JUST.NET.Test.Season.findseason,#valueof($.tree.branch.leaf),#valueof($.tree.branch.flower))`

i would like to have something like
`$findseason(...)`

in order for JUST to find my custom function, there could be a container and we could register our custom functions as such:

`JUST.NET.CustomFunctions.Add(myCustomFunctionDll, methodName)`

**Comment by Courela** [comment]
There's this option also [https://github.com/WorkMaze/JUST.net#calling-user-defined-methods-by-name](https://github.com/WorkMaze/JUST.net#calling-user-defined-methods-by-name)

**Comment by yvz5** [comment]
its as bad as the other option

**Comment by Courela** [comment]
Check #42 and #52
