### ISSUE TITLE
Check  properties

### ISSUE THREAD

**Issue by Rammun** [WorkMaze/JUST.net#4]
Hi!
How can I verify a property exist or not empty?

I tried
but it doesnt work
#ifcondition(#valueof($.BuyDate),,,#concat( buy date: ,#valueof($.BuyDate)))

Thanks in advance.

**Comment by WorkMaze** [comment]
Hi,

I have added new functions for this purpose:-

1. exists(path)
2. existsandnotempty(path)

Input:
```
{
   "BuyDate": "2017-04-10T11:36:39+03:00",
   "ExpireDate": ""
}
```

Transformer:
```
{
  "BuyDateString": "#ifcondition(#exists($.BuyDate),true,#concat(Buy Date : ,#valueof($.BuyDate)),NotExists)",
  "BuyDateString2": "#ifcondition(#existsandnotempty($.BuyDate),true,#concat(Buy Date : ,#valueof($.BuyDate)),EmptyOrNotExists)",
  "ExpireDateString": "#ifcondition(#exists($.ExpireDate),true,#concat(Expire Date : ,#valueof($.ExpireDate)),NotExists)",
  "ExpireDateString2": "#ifcondition(#existsandnotempty($.ExpireDate),true,#concat(Expire Date : ,#valueof($.ExpireDate)),EmptyOrNotExists)",
  "SellDateString": "#ifcondition(#exists($.SellDate),true,#concat(Sell Date : ,#valueof($.SellDate)),NotExists)",
  "SellDateString2": "#ifcondition(#existsandnotempty($.SellDate),true,#concat(Sell Date : ,#valueof($.SellDate)),EmptyOrNotExists)"
}
```

Output:
```
{"BuyDateString":"Buy Date : 2017-04-10T11:36:39+03:00",
   "BuyDateString2":"Buy Date : 2017-04-10T11:36:39+03:00",
   "ExpireDateString":"Expire Date : ",
   "ExpireDateString2":"EmptyOrNotExists",
   "SellDateString":"NotExists",
   "SellDateString2":"EmptyOrNotExists"
}
```

Please let me know if this solves your purpose.
Kind regards!

**Comment by Rammun** [comment]
Hi,
I updated the package, but have an error. It doesnt have a namespace of JUST.

![just1](https://user-images.githubusercontent.com/12098829/27374938-46bfc5ec-5676-11e7-9cd8-f6bb9414c17c.PNG)
![just2](https://user-images.githubusercontent.com/12098829/27374937-46bf09f4-5676-11e7-90a0-6a82bb48700c.PNG)
![just4](https://user-images.githubusercontent.com/12098829/27375221-2916a604-5677-11e7-8860-e8213b43dd7d.PNG)
![just3](https://user-images.githubusercontent.com/12098829/27374936-46be618e-5676-11e7-8ac0-dfce788773b1.PNG)


.

**Comment by WorkMaze** [comment]
Hi,
Looks like no reference to the DLL was added. Can you try to add a reference from your Packages(2.0.4) folder?

**Comment by Rammun** [comment]
When I added dll my hands then it works. New methods work good. Thank you very much!

**Comment by WorkMaze** [comment]
Glad to know.
Reagrds!
