### ISSUE TITLE
if-condition with multiple condition possibility

### ISSUE THREAD

**Issue by rskumargithub** [WorkMaze/JUST.net#41]
Hi,
as per our scenario am looking for if-condition with multiple conditions like  if (country == 'US' and (State ='TX' || State = 'AR') then return country else return 'US', is there any possibility I can achive on this , even I tried with jsonPath as below, but no luck.

"{ 'has_items' : '#ifcondition(#valueof($.items[0].answers[?(@.number == 3 && @.type == 'number')].number),3,yes,no)' }

can you help on this ?.

**Comment by rskumargithub** [comment]
yeah I used nest multiple ifconditions. thank you.

**Comment by adamgusky** [comment]
can you still use multiple if conditions for setting one value?

something to cover this case:
```
if (sun == true && clouds == true) {
 weather: "partly cloudy"
}
```
where input would be
```
{
 "sun": true,
 "clouds": true
}
```

if possible, could you share what that transform would look like?

**Comment by Courela** [comment]
Test each field separately:

```JSON
{
  "weather": "#ifcondition(#valueof($.sun),true,#ifcondition(#valueof($.clouds),true,partly cloudy,sun),rain)"
}
```
