### ISSUE TITLE
Having source root ($) as an array

### ISSUE THREAD

**Issue by raghu-romp** [WorkMaze/JUST.net#49]
I wanted to use JUST.net to transform an API response, which is an array of elements into another array. JUST.net seems to treat the root element as a JObject instead of JToken and hence the root of the JSON ($) should always be an object and not an array. 

I am currently working around by wrapping my API response inside an object and using a property accessor. Not having to deal with this unwanted wrapping would be great.

**Comment by Courela** [comment]
I heve forgotten about this one, I had some code already prepared long time ago but I wasn't comfortable with it without proper type handling, which is now in place.

Just a remark, be careful with functions that only support one result, like #valueof. If you need multiple elements' selection use #loop.

**Comment by OccamsTacKnife** [comment]
Very good, thanks for the fast response. I'll keep an eye out for an update. I'm finding this tool very useful.
