### ISSUE TITLE
A value type

### ISSUE THREAD

**Issue by Rammun** [WorkMaze/JUST.net#5]
Hi,
how can I retain a value type during a transformation?

the input:
```
{
	"id": 20,
	"active": true,
}
```

the transform:
```
{
	"typeId": "#valueof($.id)",
	"active": "#valueof($.active)"	
}
```

the output:
```
{
	"id": "20",
	"active": "True"
}
```

**Comment by WorkMaze** [comment]
Hi,

I have added support to retain Value types. Please use Nuget 2.0.5.
Regards!

**Comment by Rammun** [comment]
It works. Thank you!

But the link to the dll has to be added manually. What could be the reason?

**Comment by WorkMaze** [comment]
I will close this issue for now. I will have a look into to why you have to add the reference manually. It could be the way the dependencies are set up in the package.

**Comment by WorkMaze** [comment]
Hi again,
I have fixed the DLL reference issue. Please try downloading the latest Nuget 2.0.6.
The reference should now be added automatically. You shouldn't need to add the DLL reference manually any more.
Regards!
