### ISSUE TITLE
Error:  Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by BNeiman** [WorkMaze/JUST.net#54]
I have a simple JUST map:
**{
  "work_notes": "#valueof($.work_notes)"
}**
Works most of the time but when it is applied to the attached payload it throws "Object reference not set to an instance of an object."  The property value is escaped JSON that I'm able to unescape.
[test3.zip](https://github.com/WorkMaze/JUST.net/files/2953413/test3.zip)

What is causing the error? Is there something wrong with my data?

**Comment by Courela** [comment]
Using the latest version of JUST.Net, I was able to apply the transformer over your input file.

Code:
```C#
string input = File.ReadAllText("test3.json");
string transformer = "{ \"work_notes\": \"#valueof($.work_notes)\" }";
Console.WriteLine(JsonTransformer.Transform(transformer, input));
```

Result:
```json
{"work_notes":{"sc_cat_item":"CL-0045_CommissionAccentureDwp","sys_domain":"821dc414130ce3008a3efc04e144b097","company_sys_id":"2e2d4814130ce3008a3efc04e144b0ec","company":"Siemens Digital Workplace","number":"TASK0092242","request_item":"RITM0042584","assignment_group":"Resolve Automation","active":"true","short_description":"Update CMDB CI Field Status","variables":{"siemens_xml_payload":{"dynamic_attribute":{"transactionID":"CL-0045_CommissionAccentureDwp","contractID":"0","serialNumber":"AlexTest5","macAddress":"AF-BB-CC-DD-EE-05","hardware":"Esprimo P520","operatingSystem":"Windows 10 64 Bit","locationCode":"MCH P","company":"Siemens","building":"","room":"","floor":"","newHardware":"true","uuidAccentureDWP":"021014300000000000000000000000000136688"},"header":{"sourceSystem":"EX47-ACCENTURE-STAGE","targetSystem":"FITS-STAGE","version":"1","customerTicketID":"RITM3805879","providerTicketID":"RITM0042584","timeStamp":"2019-03-08 15:15:54","messageId":"a81a2446-7eb6-40f5-9c48-62968522f53e","processType":"ORDER","actionType":"new"},"cat_item":"d2731f52db6ce3803181d36fdf96198d","requester":"32e539bfdb97ef48f1f5cae3b9961940","receiver":"32e539bfdb97ef48f1f5cae3b9961940"}},"computer_ci_attributes":{"computer_attributes":{"clientName":"AlexTest5","UUID":"021014300000000000000000000000000136688","accentureClientStatus":"on_order","ciOwner":"Alexander Wagner","ownerGID":"Z00407PK","ownerEmail":"Z00407PK@siemens.com","serialNumber":"AlexTest5","macAddress":"AF-BB-CC-DD-EE-05","modelNumber":"Esprimo P520","reactivatedDate":"","deactivatedDate":"","decommissionedDate":"","firstInstalledDate":"","adDomainName":"","adOuPath":"","hardwareEncryption":"","ciOwnerLocation":"MCH P","countryCode":"DE","LastUpdated":"2019-02-27 00:10:34","ciStatusLastChange":"","localAdminAdd":[],"localAdminRemoved":[]}}}}
```

The thing that I see wrong in the result is parsing the string into a json object, it should return the string as it is.

**Comment by BNeiman** [comment]
Hi - Thank you!

I was running 5.1.1 and just now updated to 5.1.3 and still get the error.  Right, it seems to be treating the encoded json string as json.  These two properties are causing the error:
```
,\r\n\"localAdminAdd\":[],\r\n\"localAdminRemoved\":[]\r\n
```
So if I remove or change these two properties to strings, it works:
```
,\r\n\"localAdminAdd\":\"\",\r\n\"localAdminRemoved\":\"\"\r\n
```
Both are valid json if I unescape and test them.  How do i get JUST not to treat strings as JSON?  It should not try to serialize these, they are just strings.

**Comment by Courela** [comment]
You're using package JUST v5.1.3, switch to JUST.Net v2.0.2, it's the one that is being updated, with support for both .Net Framework and .Net Core

**Comment by Courela** [comment]
Responding to your question, since the code works mainly with strings, when there's the need to deserialize to an object, it searches for LF (\n) inside the string, and if found it assumes it's an object.

I already have some code that works with proper types, and in your specific case it returns a string, I'm just waiting for the opened pull request to be approved or rejected, so I can merge it and make a new pull request.

**Comment by BNeiman** [comment]
Thanks Nuno - Looking forward to the update.
