### ISSUE TITLE
Not to able to skip iteration in loop.

### ISSUE THREAD

**Issue by mdevale** [WorkMaze/JUST.net#55]
I want to transform Json that contains array. In one scenario, i want to skip iteration in loop. Is it possible to skip iteration on condition. As of now i want to skip first and last iteration

**Comment by Courela** [comment]
If you know array's length shorthand you can build a proper JsonPath expression that will filter the wanted positions, then apply it with #loop function:

Input:
```json
{ "test": [ { "id": 1, "dummy": "Item1", "ignored": "bla" }, { "id": 2, "dummy": "Item2", "ignored": "bla" }, { "id": 3, "dummy": "Item3", "ignored": "bla" }, { "id": 4, "dummy": "Item4", "ignored": "bla" } ]}
```

Transformer:
```json
{ "iteration": { "#loop($.test[1:3:1])": { "id": "#currentvalueatpath($.id)", "dummy": "#currentvalueatpath($.dummy)" } } }
```

Result:
```json
{ "iteration": [ { "id": 2, "dummy": "Item2" }, { "id": 3, "dummy": "Item3" } ] }
```

**Comment by mdevale** [comment]
Normally array's length is not fixed. It can be any number. Can i apply any condition with #currentIndex() or #lastIndex() in loop.

**Comment by Courela** [comment]
Those functions are only available inside a #loop function, so you will end up with something generated for first and last element of the array, which as I understand is what you don't want.

Besides what I mentioned, I don't see any other way of doing it as it stands.
One change that can be done to accommodate this it to allow having functions as argument for #loop function, so you can create the JsonPath expression dynamically. One will need a function to give the array's size, as described in #56.

**Comment by mdevale** [comment]
$.test[1:3:1] what it indicates. How it will skip first and last iteration.

**Comment by Courela** [comment]
[JsonPath Expressions](https://goessner.net/articles/JsonPath/index.html#e2)

The first number is the start index (zero based), the second is the end index, the third is the step (optional)

**Comment by Courela** [comment]
Currently #valueof function does not support multiple tokens as result, in other words, selecting multiple values and return the result as an array.
