### ISSUE TITLE
How to rename a property name in a node

### ISSUE THREAD

**Issue by zhaomuzhi** [WorkMaze/JUST.net#6]
Considering transforming this JSON 
{
    "answers":[{"value": [{"id":1}]}]
}
to
{
    "results":[{"spec-Id":1}]
}

I can write some transformation file like
{
  "results": "#valueof($.answers[0].value)"
}
But how can I rename "Id" to "spec-Id"? Probably I can have a custom function to do the conversion. But I will lose the capability to reuse existing function that has been defined in the custom function, and if the $.answers[0].value becomes complex, the custom function will become big and it's meaningless to use the transform template.

**Comment by WorkMaze** [comment]
Hi,

The transformation below would give you the desired result:-

{  
  "results": [ { "spec-id":"#valueof($.answers[0].value[0].id)" } ]
}

Please let me know if this works for you.
Regards!

**Comment by WorkMaze** [comment]
Closing this issue for now. Please let me know in case you need more assistance.

**Comment by zhaomuzhi** [comment]
I think your solution only works if there is only one element in $.answers[0].value, but what if it has multiple elements and I don't know the count of it?

**Comment by WorkMaze** [comment]
Hi,
Try the Array Looping functions.

Input:-

`{
  "answers": [
    {
      "value": [
        { "id": 1 },
        { "id": 2 },
        { "id": 3 }
      ]
    }
  ]
}`

Transformer:-

`{
  "results": {
    "#loop($.answers[0].value)": { "spec-Id": "#currentvalueatpath($.id)" }
  }`
}

Output:-
`{"results":[{"spec-Id":"1"},{"spec-Id":"2"},{"spec-Id":"3"}]}`

Let me know if this works.
