### ISSUE TITLE
Simple functions like add, subtract fails in Azure function using JUST.NETCore

### ISSUE THREAD

**Issue by sipredn** [WorkMaze/JUST.net#64]
Thanks for the beautiful tool for JSON transformation.
Quick question: I tried the examples that you have provided in GitHub using Visual Studio 2017 - Console application. Really works well.
When I tried to use the same piece of code and same example in Azure function, it fails and I get the below error. I have used JUST.NETCore in azure function
It happens for all add, subtract, multiply and divide also.
Simple example I have used
Input.json
{
  "d": [ "one", "two", "three" ],
  "numbers": [ 1, 2, 3, 4, 5 ]
}
Tranformer:
{
  "mathresult": {
    "add": "#add(#valueof($.numbers[0]),3)",
    "subtract": "#subtract(#valueof($.numbers[4]),#valueof($.numbers[0]))",
    "multiply": "#multiply(2,#valueof($.numbers[2]))",
    "divide": "#divide(9,3)",
	"round": "#round(10.005,2)"
  }
}
Error:
Executed 'TranformData' (Failed, Id=)
[6/5/2019 3:20:18 PM] System.Private.CoreLib: Exception while executing function: TranformData. JUST.NETCore: Error while calling function : **#add(#valueof($.a),#valueof($.b))** - Exception has been thrown by the target of an invocation.

All I need is 
Input : a=10, b=20
transformer:
"add": "#add(#valueof($.a),#valueof($.b))"
Even this is also failing in Azure function using JUST.NETCore
Please do the needful

**Comment by sivaprasadrednam3055** [comment]
Interesting part is #**xadd** works for adding two numbers but plain **add** and **subtract** doesn't work. I get the below error for subtract
Executed 'TranformData' (Failed, Id=9c029397b)
[6/5/2019 4:49:16 PM] System.Private.CoreLib: Exception while executing function: TranformExtractedData. JUST.NETCore: Error while calling function : #subtract(#valueof($..b),#valueof($..a)) - Object of type 'System.Int64' cannot be converted to type 'System.String'.

**Comment by Courela** [comment]
I'm not familiar with Azure, but my wild guess would be reflection issues. 
How do you reference JUST.Net library in Azure function? That could be an issue since the functions are not called directly, they are referenced through reflection.

**Comment by sipredn** [comment]
Its the newtonsoft.json compatibility issue Microsoft SDKs Newtonsoft vs JUST.NetCore Newtonsoft. I have downloaded your code and verified it. Now the functions are working as expected. Thanks for the support. Appreciate your timely response.
