### ISSUE TITLE
String Contains: Can the second parameter be a string array?

### ISSUE THREAD

**Issue by sipredn** [WorkMaze/JUST.net#66]
#ifcondition(#stringcontains(#valueof($.d[0]),n),true,yes,no): Example from Just.Net git
In this example, we are trying to hard code **n**, instead can we check value of $.d[0] contains in an array of string [a,b,c,n].
do we have a way where we can do something like this?
#ifcondition(#stringcontains(#valueof($.d[0]),[a,b,c,n]),true,yes,no)

**Comment by Courela** [comment]
If I understand correctly you want something like "string contains one of these strings". #stringcontains will not work, since it's arguments are two strings. 
The only way I see to do this is to use #loop (assuming that you have the test array in your input json), but then you'll end up with an array telling if test string contains each element of the test array:

Input:
```JSON
{ 
  "d": [ "one", "two", "three" ], 
  "values": [ "o", "c", "n" ]
}
``` 

Transformer:
```JSON
{
  "result": { 
    "#loop($.values)": { 
      "test": "#ifcondition(#stringcontains(#valueof($.d[0]),#currentvalue()),true,yes,no)" 
    } 
  } 
}
```

Result:
```JSON
{
  "result": [
    { "test": "yes" },
    { "test": "no" },
    { "test": "yes" }
  ]
}
```

**Comment by sipredn** [comment]
Thanks for your snippet. Appreciate it. I need to use stringcontains in an if condition so I have tried to include the logic in another custom method which is similar to stringcontains and it works fine.
 #ifcondition(#stringcontainsinanarray(#currentvalueatpath($.valuetobechecked),string1,string2,string3,string4),true,yes,no))

public static bool stringcontainsinanarray(object[] list)
        {
            bool result = false;

            if (list.Length >= 2)
            {               
                if (list[0] != null)
                {
                    var val = list[0].ToString();
                    var sublist = list.Skip(1).ToList();
                    foreach (var item in sublist)
                    {
                        if (val.Contains(item.ToString()))
                        {
                            result = true;
                            break;
                        }
                    }
                }
            }
            return result;
        }
