### ISSUE TITLE
control characters

### ISSUE THREAD

**Issue by Rammun** [WorkMaze/JUST.net#7]
Thank you for solving the problem of the installation of the package.
But now another problem - it is control characters.

the input:
```
{
	"ArrivePlace": "Bryansk, \"Parkovaya\""
}
```

the exception:
```
Newtonsoft.Json.JsonReaderException: Additional text encountered after finished reading JSON content: ,. Path '', line 1, position 0.
   в Newtonsoft.Json.JsonTextReader.Read()
   в Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   в Newtonsoft.Json.Linq.JToken.Parse(String json)
   в JUST.JsonTransformer.RecursiveEvaluate(JToken parentToken, String inputJson, JArray parentArray, JToken currentArrayToken)
   в JUST.JsonTransformer.Transform(String transformerJson, String inputJson)
```

**Comment by WorkMaze** [comment]
Hi,
Please download the latest Nuget 2.0.8.

Input:-
`{
  "ArrivePlace": "Bryansk, \"Parkovaya\""
}`

Transformer:-
`{
  "Destination": "#valueof($.ArrivePlace)"
}`

Output:-
`{"Destination":"Bryansk, \"Parkovaya\""}`

Regards!

**Comment by Rammun** [comment]
There are no errors. Thank you.

**Comment by WorkMaze** [comment]
Good to know.
