### ISSUE TITLE
Output JSON root as Array

### ISSUE THREAD

**Issue by MysterDru** [WorkMaze/JUST.net#77]
I'm wondering if it's possible to have the transformer output it's result as an array in the JSON root. 

I'm working on a process that needs to transform data to make a POST body request to an API, which accepts an array as the root of the body. 

Right now, you can use a JSON Array as an input (#49) but there doesn't seem to be away to have the root of the output be an array; only an object in the root. 

Given I have an input that looks like:
```
[{
	"id" : 1,
	"cnt" : 100,
	"rowNum" : 1,
	"col" : 1
  },
  {
	"id" : 2,
	"cnt" : 89,
	"rowNum" : 1,
	"col" : 1
  }]
```

and i want an output that looks like 
```
[{
	"key" : 1,
	"quantity" : 100,
	"rows" : 1,
	"columns" : 1
},
{
	"key" : 2,
	"quantity" : 89,
	"rows" : 1,
	"columns" : 1
}]
```

I would expect that i could create a transformer like this:
```
{
    "#" : {
        "#loop($)" : {
            "key" : "#valueatcurrentpath($.id)",
            "quantity" : "#valueatcurrentpath($.cnt)",
            "rows" : "#valueatcurrentpath($.rowNum)",
            "columns" : "#valueatcurrentpath($.col)"
        }
    }
}
```

However, using such a transformer results in an output of 
```
{ } 
```

I expect this is because the framework does not support creating an array output.

The closest I can currently get is with a transformer like:
```
{
    "data" : {
        "#loop($)" : {
            "key" : "#valueatcurrentpath($.id)",
            "quantity" : "#valueatcurrentpath($.cnt)",
            "rows" : "#valueatcurrentpath($.rowNum)",
            "columns" : "#valueatcurrentpath($.col)"
        }
    }
}
```

which will give me an output of
```
{
  "data" :  [{
	"key" : 1,
	"quantity" : 100,
	"rows" : 1,
	"columns" : 1
  },
  {
	"key" : 2,
	"quantity" : 89,
	"rows" : 1,
	"columns" : 1
  }]
}
```

Are there plans to support this, or a is there a recommended work around? I am trying to limit the amount of custom that needs to be run after the transformation.

**Comment by Courela** [comment]
As it stands this is not possible, mainly because output is expected to have a root property, an array doesn't comply with that.
By the way, it's "#currentvalueatpath" not "#valueatcurrentpath".

**Comment by MysterDru** [comment]
That's fair. Thanks for responding @Courela. 

I ended up working around this limitation by having my logic expect a root content property in the output json. I then remove the root property and use the remaining JToken as the new root before continuing with my logic. 

I'll close this issue then.

**Comment by Courela** [comment]
You're not the first one to ask for this feature, and it makes total sense, for example in a REST Api response.
I'm working on a solution for this, I already have it working for what you asked, I just need to confirm that nothing else breaks, because it involves messing with the root element.
