### ISSUE TITLE
The valueof with a wrong jsonPath throws NullReferenceException

### ISSUE THREAD

**Issue by Baryad** [WorkMaze/JUST.net#80]
Hello!
I'm a new user of the JUST.net library version 3.0.1
Trying to transform one json to another one and troubleshoot the issues in transformations.

The valueof with a wrong jsonPath as a parameter throws NullReferenceException see

`DataTransformer.Transform("{\"Person\":{\"Name\": \"#valueof($.nameX)\"}}", "{\"name\": \"MyName\"}")`

The expected behavior is to report the string which causes the issue. The location of the string in a transformer string will also help to troubleshoot the use cases.
If there are many json transformations in a large transformer string it's hard to guess just by the NullReferenceException what went wrong.

Thank you very much for the library.

**Comment by Courela** [comment]
Hi,
if you want a Json as result you should use JsonTransformer instead of DataTransformer.

Nevertheless DataTransformer should work as well, and your point is valid, but DataTransformer has not been so actively maintained as JsonTransformer.

**Comment by Baryad** [comment]
Thank you!
I've tried to use this
`JsonTransformer.Transform("{\"Person\":{\"Name\": \"#valueof($.name1)\"}}", "{\"name\": \"MyName\"}", new JUSTContext() { EvaluationMode = EvaluationMode.Strict })`
 and results is `{"Person":{"Name":null}}` with EvaluationMode Strict
Could you help me how to get the exception in case of wrong json transformation parameters.

**Comment by Courela** [comment]
The JsonPath evaluation is done by Newtonsoft Json's library, it's out of JUST.Net's control. 
It accepts "invalid paths", as long as the JsonPath syntax is correct. We can't just check for null values because "null" can be a valid result for a JsonPath query (if a property has a null value).

**Comment by Baryad** [comment]
Ok. Then unexpected null value would be the indication that something went wrong. That can be unit tested.
Thank you.
