### ISSUE TITLE
Is it possible to flatten array?

### ISSUE THREAD

**Issue by jonasro** [WorkMaze/JUST.net#82]
If I have the following structure:
```
{
	"Order": {
		"OrderId": 123456,
		"OrderLines": [{
				"SkuId": 357159,
				"Quantity": 12.5
			},
			{
				"SkuId": 484186,
				"Quantity": 10
			}
		]
	}
}
```

Could I use JUST.net to flatten it into this:
```
[
  {
    "OrderId": 12346,
    "SkuId": 357159,
    "Quantity": 12.5
  },
  {
    "OrderId": 123456,
    "SkuId": 484186,
    "Quantity":  10 
  }
]
```

**Comment by Courela** [comment]
Yes, it is possible. The only thing here that might not work is that you must have an object as result, you can't have an array as root.

Transformer will go like this:
```JSON
{  
  "result": { 
    "#loop($.Order.OrderLines)": { 
      "OrderId": "#valueof($.Order.OrderId)", 
      "SkuId\": "#currentvalueatpath($.SkuId)", 
      "Quantity": "#currentvalueatpath($.Quantity)"
    }
  }
}
```

The problem of returning an array was already mentioned a few times (#77 is an example), I've already have a working version (here)[https://github.com/Truphone/JUST.net/tree/output_array].

**Comment by jonasro** [comment]
Thank you. That worked :) 
It would have been nice to have support for returning array, but I can probably work around it.
