### ISSUE TITLE
Check if field exists in loop

### ISSUE THREAD

**Issue by Trisped** [WorkMaze/JUST.net#83]
How do I check if a field exists in a loop?
Input:
`[{
        "id": "id1",
        "category": "cat1"
    }, {
        "id": "id2",
    }
]
`
Transformation:
`{
    "items": {
        "#loop($)": {
            "#ifgroup(#exists($.category))": {"category":"#currentvalueatpath($.category)"}
        }
    }
}
`

The problem is I don't know how to set the path for #exists.  I have tried "$.category", "$.[0].category", "$[0].category", and a few others, but #exists always returns false.
It would be nice if there was a #currentexistsatpath function, but I figure I can use #eval, #xconcat, and #currentindex to the same effect, if I could just figure out what path to pass to #exists.

**Comment by RollsRoise** [comment]
We've used it in conjunction with the #ifcondition with good results.  It would seem that the #exists looks correct, but haven't used it with ifgroup.  

From the documentation, I think this is similar to what you're trying?
  "SellDateString2": "#ifcondition(#existsandnotempty($.SellDate),
  true,#concat(Sell Date : ,#valueof($.SellDate)),EmptyOrNotExists)"

https://www.codeproject.com/Articles/1187172/JUST-JSON-Under-Simple-Transformation

**Comment by Trisped** [comment]
Hi @RollsRoise,
I saw that example at https://github.com/WorkMaze/JUST.net but it does not address how to get the path when in a loop.  I tried using $.category as the path (among other things) but exists returns false.  It returns true if I just use $, but I need the path to the category not the root.

**Comment by RollsRoise** [comment]
@Trisped yep, sorry, I read that at first...but clearly forgot about a minute later. :(  Agree, would be useful.  We've really not cared much about the existence of elements tbh tho...if its there, great - otherwise will get null value which gets dropped eventually anyhow in our world

**Comment by Courela** [comment]
Your transformation is correct, when looping function #exists assumes the current item as root. Unfortunately there's a bug in current release (JUST.net 3.0.1) that affects #exists under loop.
If you would like you can try code from [this branch](https://github.com/Truphone/JUST.net/tree/develop), which already has some more fixes, including this one.
,

**Comment by AvinFernando** [comment]
Does this bug also affect #stringequals under a loop? Because I am having trouble using that in 3.0.1. I wrote this test to reproduce the issue:

`        [Fact]
        public void ReproduceLoopError()
        {
            var transform = "{ \"names\": { \"#loop($.people)\":{ \"#ifgroup(#stringequals(#currentvalueatpath($.name),Bob))\": {\"alias\":\"Robert\"}, \"first\":\"#currentvalueatpath($.name)\" }} }";
            var source = "{\"people\": [{\"name\": \"Alice\"}, {\"name\": \"Bob\"}, {\"name\": \"Chuck\"}]}";
            var result = JUST.JsonTransformer.Transform(transform, source);
            Assert.Equal("{\"names\":[{\"first\":\"Alice\"},{\"alias\":\"Robert\"\"first\":\"Bob\"},{\"first\":\"Chuck\"}]}", result);
        }`

**Comment by Courela** [comment]
I think it affects every function that uses JsonPath and is not specific to loops (#currentvalueatpath, #currentindex,...), and also #valueof.

**Comment by Trisped** [comment]
Thanks for the feed back @Courela, I don't have time to look into this today, but I plan on downloading the updated code you linked and testing it tomorrow.  I will let you know how it goes.

**Comment by Courela** [comment]
If you just want to use the same code base as version 3.0.1, you can use code from pull request #84

**Comment by Trisped** [comment]
Thanks @Courela, it works.  Any idea when these changes would be released as a nuget package?

**Comment by Courela** [comment]
It's not up to me.
