### ISSUE TITLE
3.0.2 broke #ifgroup  in loop

### ISSUE THREAD

**Issue by Trisped** [WorkMaze/JUST.net#85]
I have not looked at the code, but it seems like it is always evaluating to false.

Input:
`[{ "id": "id1", "category": "cat1" }, { "id": "id2", } ]`
Transformation:
`{ "items": { "#loop($)": { "#ifgroup(#exists($.category))": {"category":"#currentvalueatpath($.category)"} } } }`
Expected Output:
`{"items":[{"category":"cat1"},{}]}`
Actual Output:
`{"items":[{},{}]}`

It was working in @Courela 's [branch](https://github.com/Truphone/JUST.net/tree/develop), but I am not sure that branch had the latest master since Transform was not a static method on JsonTransformer (required an instance in Courela's branch).

The example in the readme works fine, so it appears to be an issue with #ifgroup in loops.
This is related to Issue #83 and pull request #84

**Comment by Courela** [comment]
There was a bug in #ifgroup when inside a loop.

The [repo](https://gitbub.com/Truphone/JUST.net) I'm working on has master branch equal to this, but develop branch already has a lot of code changes (some improvements and some new feature). I plan to gradually introduce them here.

**Comment by Trisped** [comment]
The new release (3.0.3) fixed this issue.
Thanks @Courela and @WorkMaze
