### ISSUE TITLE
#tostring (and other conversion) function(s) does not work

### ISSUE THREAD

**Issue by yurtcu** [WorkMaze/JUST.net#87]
Hi,

I am trying to #concat some values that one of them is integer and others are string. #concat cannot concatenate integer and string. So I moved to convert integer value to string by using #tostring function. I've tried many things and finally tried exactly your sample input and transformer files under https://github.com/WorkMaze/JUST.net#-type-convertions title but did not work!

I've tried that on both .Net and .Net core versions but no chance. Is it really working? I am getting this error:

> Error while calling function : #toboolean(#valueof($.booleans.affirmative_string)) - Object reference not set to an instance of an object.

Also I've tried to remove other parts of transformer and leaved just this:
```
{
  "strings": {
    "integer": "#tostring(#valueof($.strings.integer))"
  }
}
```

...got this error:

> Error while calling function : #tostring(#valueof($.strings.integer)) - Object reference not set to an instance of an object.

Regards,
Barış

**Comment by Courela** [comment]
Well, all the examples in Readme have unit tests running them, so they work.
Which version are you using exactly? On [version 3.0.3](https://www.nuget.org/packages/JUST.net/3.0.3) it is working, I've just tried it.

**Comment by yurtcu** [comment]
I've used 5.1.3 for .Net and 2.1.3 for .Net Core. There is no 3.0.3 in the nuget packages I've used (You can see screenshots below). I think there are different packages, there is JUST.net package that have version 3.0.3 (that is the link you've shared), I've tried it on both .Net project and .Net Core project  and it's working fine.

Thank you very much.

![image](https://user-images.githubusercontent.com/25557405/74522082-9b8b3100-4f2b-11ea-897a-8c8705be6c72.png)

![image](https://user-images.githubusercontent.com/25557405/74531005-8c60af00-4f3c-11ea-9c42-831b559bbc01.png)

**Comment by Courela** [comment]
As stated in ReadMe, those packages are not maintained anymore, there's no need to split since .Net Standard works for both .Net Framework and .Net Core.

**Comment by yurtcu** [comment]
You're right. I missed out that point in Readme.
