### ISSUE TITLE
#ifgroup always adds to end of the result

### ISSUE THREAD

**Issue by yurtcu** [WorkMaze/JUST.net#88]
Hi, 

#ifgroup results appears always at the end. For example:

Input:
```
{
  "Gear": "Auto",
  "Fuel": "Diesel"
}
```

...and transformer:

```
{
  "CarInfo": {
    "Wheels": "4",
    "Color": "Blue",
    "Doors": "2",
    "#ifgroup(#stringequals(#valueof($.Gear),Auto))": {
      "GearType": "DSG"
    },
    "Engine": "1.6",
    "#ifgroup(#stringequals(#valueof($.Fuel),Diesel))": {
      "Noise": "High"
    },
    "Climate": "Auto"
  }
}
```
Expected result:
```
{
  "CarInfo": {
    "Wheels": "4",
    "Color": "Blue",
    "Doors": "2",
    "GearType": "DSG",
    "Engine": "1.6",
    "Noise": "High",
    "Climate": "Auto"
  }
}
```
But actual result is here:
```
{
  "CarInfo": {
    "Wheels": "4",
    "Color": "Blue",
    "Doors": "2",
    "Engine": "1.6",
    "Climate": "Auto",
    "GearType": "DSG",
    "Noise": "High"
  }
}
```

Also, is it possible to apply #ifgroup to array items?

**Comment by Courela** [comment]
The fields' order should not matter in JSON, as stated [here](https://www.json.org/json-en.html):

> An object is an unordered set of name/value pairs.

About #ifgroup, do you mean use it inside #loop? If so, you can.

**Comment by yurtcu** [comment]
> The fields' order should not matter in JSON, as stated [here](https://www.json.org/json-en.html):
> 
> > An object is an unordered set of name/value pairs.

It matters in our scenario. That was only a sample, our scenario is different and item's document order is important.

> 
> About #ifgroup, do you mean use it inside #loop? If so, you can.

No, I mean for example the "Pink" color should appear ONLY if Sex equals to "Female": (and order is important in here too)
```
{
  "Colors": [
    "Blue",
    "Black",
    "Pink",   <-- #ifgroup(#stringequals(#valueof($.Sex),Female))
    "Green"
  ]
}
```

**Comment by Courela** [comment]
There's no need to use #ifgroup for this, JsonPath allows filtering on arrays. The only problem here is that #valueof does not work if JsonPath returns multiple results, so we need to do a workaround using #loop (and some dynamically built JsonPath).

```JSON
{
  "Colors": {
    "#loop(#xconcat($.Colors, #ifcondition(#valueof($.Sex),Female,,[?(@ != 'Pink')])))": #currentvalue()" 
  }
}
```
