### ISSUE TITLE
Array looping set target value as {} if the source value is empty array 

### ISSUE THREAD

**Issue by rkg823** [WorkMaze/JUST.net#89]
Hi, Array looping set target value as {} if the source value is empty array.
below is the scenario. 
input json -
 {
scars_marks: []
} 
transformer  -
 {
  "ScarsMarks": {
    "#loop($.scars_marks)": {
      "description": "#currentvalueatpath($.description)"
    }
  }
}
output - 
{
  "ScarsMarks": {}
}

expected output - 
{
  "ScarsMarks": []
}
It would be really good if we can pass default value in the loop function #loop($.scars_marks, [])
 any guidance would be greatly appreciated.

**Comment by Courela** [comment]
From my perspective you shouldn't have to define a default value, looping over an empty array should return an empty array.
I've fixed that on #90

**Comment by rkg823** [comment]
> From my perspective you shouldn't have to define a default value, looping over an empty array should return an empty array.
> I've fixed that on #90

For some scenario we might need to have 'null' instead of empty array. I believe it would be good to have feature.
