### ISSUE TITLE
dotnetcore support

### ISSUE THREAD

**Issue by ShrenikOne** [WorkMaze/JUST.net#9]
Is it going to be supported in .NET Standard?, Also will it be possible to expose Stream APIs, since if we have large data which required transformation, what will be memory footprint. In our case data might be large as 4 MB.

**Comment by WorkMaze** [comment]
Hi,
I have added dotnetcore support:-

`Install-Package JUST.NETCore `

Exposing stream APIs might be a bit difficult as the API needs to read the entire JSON and parse it to be able to read elements by JSON path.

I will definitely look into if it would be possible at all to support a Steam based API for larger files.
