### ISSUE TITLE
Math functions samples doesn't work

### ISSUE THREAD

**Issue by tresoldigiorgio** [WorkMaze/JUST.net#93]
The sample code for math function throw an error 

Unhandled exception. System.Exception: Error while calling function : #ifcondition(#mathequals(#valueof($.numbers[2]),3),true,yes,no) - Error while calling function : #mathequals(#valueof($.numbers[2]),3) - Object reference not set to an ins
tance of an object.
   at JUST.JsonTransformer.parseFunction(String functionString, String inputJson, JArray array, JToken currentArrayElement)
   at JUST.JsonTransformer.RecursiveEvaluate(JToken parentToken, String inputJson, JArray parentArray, JToken currentArrayToken)
   at JUST.JsonTransformer.RecursiveEvaluate(JToken parentToken, String inputJson, JArray parentArray, JToken currentArrayToken)
   at JUST.JsonTransformer.RecursiveEvaluate(JToken parentToken, String inputJson, JArray parentArray, JToken currentArrayToken)
   at JUST.JsonTransformer.Transform(String transformerJson, String inputJson)

the input is 
{
  "stringref": "thisisandveryunuasualandlongstring",
  "numbers": [ 1, 2, 3, 4, 5 ]
}
and the transformer is
{
  "stringresult": {
    "lastindexofand": "#lastindexof(#valueof($.stringref),and)",
    "firstindexofand": "#firstindexof(#valueof($.stringref),and)",
    "substring": "#substring(#valueof($.stringref),9,11)",
    "concat": "#concat(#valueof($.menu.id.file),#valueof($.menu.value.Window))",
	"length_string": "#length(#valueof($.stringref))",
	"length_array": "#length(#valueof($.numbers))"
  },
  "mathresult": {
    "add": "#add(#valueof($.numbers[0]),3)",
    "subtract": "#subtract(#valueof($.numbers[4]),#valueof($.numbers[0]))",
    "multiply": "#multiply(2,#valueof($.numbers[2]))",
    "divide": "#divide(9,3)",
	"round": "#round(10.005,2)"
  }
}

thanks

**Comment by Courela** [comment]
Which version are you using?

**Comment by tresoldigiorgio** [comment]
<PackageReference Include="JUST.NETCore" Version="2.1.3" />

this is my code

//read input from JSON file
            string input = File.ReadAllText("Input.json");
            //read the transformer from a JSON file
            string transformer = File.ReadAllText("Transformer.json");
            // do the actual transformation
            string transformedString = JsonTransformer.Transform(transformer, input);
            Console.WriteLine(JObject.Parse(transformedString).ToString(Formatting.Indented));
            Console.WriteLine("Press ENTER to EXIT");

**Comment by Courela** [comment]
Use [JUST.net](https://www.nuget.org/packages/JUST.net/) package, JUST.NETCore is deprecated.
