### ISSUE TITLE
Double looping array

### ISSUE THREAD

**Issue by mtdepippo** [WorkMaze/JUST.net#96]
Hi guys.
I have this kind of array
{
  "score_PCS": [     
    {
      "data": "2020-04-08T10:20:21.335+00:00",
      "score": [
        {
          "score_type": "pcs_tot",
          "score_value": 0.5
        },
        {
          "score_type": "pcs_help",
          "score_value": 0.46
        },
        {
          "score_type": "pcs_rum",
          "score_value": 0.5
        },
        {
          "score_type": "pcs_mag",
          "score_value": 0.63
        }
      ]
    },
    {
      "data": "2020-04-09T10:22:03.267+00:00",
      "score": [
        {
          "score_type": "pcs_tot",
          "score_value": 0.38
        },
        {
          "score_type": "pcs_help",
          "score_value": 0.42
        },
        {
          "score_type": "pcs_rum",
          "score_value": 0.35
        },
        {
          "score_type": "pcs_mag",
          "score_value": 0.38
        }
      ]
    },
    {
      "data": "2020-04-09T10:23:05.748+00:00",
      "score": [
        {
          "score_type": "pcs_tot",
          "score_value": 0.44
        },
        {
          "score_type": "pcs_help",
          "score_value": 0.38
        },
        {
          "score_type": "pcs_rum",
          "score_value": 0.5
        },
        {
          "score_type": "pcs_mag",
          "score_value": 0.5
        }
      ]
    }
  ]
}

and I'd like to obtain this array, grouped by 4 different types of scores with the "data"property copied from the first array of each element.

{
    "score_pcs_tot": {
        {
            "score_data": "2020-04-08T10:20:21.335+00:00",
            "score_type": "pcs_tot",
            "score_value": 0.5
        },
        {
            "score_data": "2020-04-09T10:22:03.267+00:00",
            "score_type": "pcs_tot",
            "score_value": 0.38
        },
        {
            "score_data": "2020-04-09T10:23:05.748+00:00",
            "score_type": "pcs_tot",
            "score_value": 0.44
        }
    },
    "score_pcs_help": {
        {
            "score_data": "2020-04-08T10:20:21.335+00:00",
            "score_type": "pcs_help",
            "score_value": 0.46
        },
        {
            "score_data": "2020-04-09T10:22:03.267+00:00",
            "score_type": "pcs_help",
            "score_value": 0.42
        },
        {
            "score_data": "2020-04-09T10:23:05.748+00:00",
            "score_type": "pcs_help",
            "score_value": 0.38
        }
    },
    "score_pcs_rum": {
        {
            "score_data": "2020-04-08T10:20:21.335+00:00",
            "score_type": "pcs_rum",
            "score_value": 0.5
        },
        {
            "score_data": "2020-04-09T10:22:03.267+00:00",
            "score_type": "pcs_rum",
            "score_value": 0.35
        },
        {
            "score_data": "2020-04-09T10:23:05.748+00:00",
            "score_type": "pcs_rum",
            "score_value": 0.5
        }
    },
    "score_pcs_mag": {
        {
            "score_data": "2020-04-08T10:20:21.335+00:00",
            "score_type": "pcs_mag",
            "score_value": 0.63
        },
        {
            "score_data": "2020-04-09T10:22:03.267+00:00",
            "score_type": "pcs_mag",
            "score_value": 0.38
        },
        {
            "score_data": "2020-04-09T10:23:05.748+00:00",
            "score_type": "pcs_mag",
            "score_value": 0.5
        }
    }
}

How can I obtain the desiderable array from that input (using JUST.net package)?
Thanks

**Comment by Courela** [comment]
It could be done with one loop only, using [Bulk functions](https://github.com/WorkMaze/JUST.net#bulk-functions). The problem is bulk functions don't work with loops currently, I've corrected it in #97.

The transformer will be:
```
{
  "score_pcs_tot": {
    "#loop($.score_PCS)": {
      "#": ["#copy($.score[?(@.score_type=='pcs_tot')])"],
      "score_data": "#currentvalueatpath($.data)"
    }
  },
  "score_pcs_help": {
    "#loop($.score_PCS)": {
      "#": ["#copy($.score[?(@.score_type=='pcs_help')])"],
      "score_data": "#currentvalueatpath($.data)"
    }
  },
  "score_pcs_rum": {
    "#loop($.score_PCS)": {
      "#": ["#copy($.score[?(@.score_type=='pcs_rum')])"],
      "score_data": "#currentvalueatpath($.data)"
    }
  },
  "score_pcs_mag": {
    "#loop($.score_PCS)": {
      "#": ["#copy($.score[?(@.score_type=='pcs_mag')])"],
      "score_data": "#currentvalueatpath($.data)"
    }
  }
}
```

By the way, your output has a typo: 
```
{
  "score_pcs_tot": { //this should be a square bracket
    {
      "score_data": "2020-04-08T10:20:21.335+00:00",
...
```
