### ISSUE TITLE
Is it possible to compare different arrays?

### ISSUE THREAD

**Issue by mtdepippo** [WorkMaze/JUST.net#98]
Hi guys. 
I'm trying to compare three different arrays and do not know if is possible to do it (or maybe what's the correct syntax to do it).
Can you help me?

I have this three arrays
{
  "procedures": [
    {
      "codice_prest": "PR-01",
      "id_paz": "Patient/p1",
      "id_med": "Practitioner/d1"
    },
    {
      "codice_prest": "PR-02",
      "id_paz": "Patient/p2",
      "id_med": "Practitioner/d2"
    }
  ],
  "patients": [
    {
      "id": "p1",
      "name": "Ambrogio Rocher"
    },
    {
      "id": "p2",
      "name": "Mia Martini"
    }
  ],
  "doctors": [
    {
      "id": "d1",
      "full_name": "Simone Rossi"
    },
    {
      "id": "d2",
      "full_name": "Davide Verdi"
    }
  ]
}
**AND I'd like to replace the references contained in the "procedures" array with the names of patients and doctors comparing with properties in the following bullet list:** 

- "procedures.id_med" with "doctors.id"
- "procedures.id_paz" with "patients.id"

**so that I can obtain this final result:**

{
    "final": [
      {
        "codice_prest": "PR-01",
        "name paz": "Ambrogio Rocher",
        "id_med": "Davide Verdi"
      },
      {
        "codice_prest": "PR-02",
        "id_paz": "Mia Martini",
        "id_med": "Simone Rossi"
      }
    ]
}

**Comment by Courela** [comment]
With current version (3.0.5) I don't see an easy way to do it, maybe with multiple transformations, using #applyover functions. I'm working on a feature that might help, nested loops, but it's not ready yet,

**Comment by mtdepippo** [comment]
Would you mind providing me any example of #applyover function?

**Comment by Courela** [comment]
After all what's preventing a simple solution is the absence of an "escape" for special characters (#60), I'll have to go back at this, it's been there for a while now... Parsing functions with parenthesis inside jsonpath expressions breaks the parameters.

After this it will be as easy as this:
```
{
  "final": {
    "#loop($.procedures)": { 
      "codice_prest": "#currentvalueatpath($.codice_prest)", 
      "id_paz": "#valueof(#xconcat($.patients[?<escape goes here>(@.id==', #currentvalueatpath($.id_paz),'<escape goes here>)].id))", 
      "id_med": "#valueof(#xconcat($.doctors[?<escape goes here>(@.id==', #currentvalueatpath($.id_med),'<escape goes here>)].id))"
    } 
  }
}
```

**Comment by mtdepippo** [comment]
Hi @Courela  ...Thanks a lot for your feedback!
Would you mind providing me some example of "escape"character or symbol I can type in the transformation?

**Comment by Courela** [comment]
It's not supported yet, therefor the issue #60 
I can try to find a solution, with the current version, at the weekend.

**Comment by Courela** [comment]
I couldn't find a solution in on go, only using two transformations, using the result of the first one as input of the second:

```
//first
{
  "procedures": {
    "#loop($.procedures)": {
      "codice_prest": "#currentvalueatpath($.codice_prest)",
      "id_med": "#currentvalueatpath($.id_med)",
      "id_paz": "#currentvalueatpath($.id_paz)",
      "start_paz": "$.patients[?(@.id=='",
      "start_med": "$.doctors[?(@.id=='",
      "end": "')]"
    }
  },
  "patients": {
    "#loop($.patients)": "#currentvalue()"
  },
  "doctors": {
    "#loop($.doctors)": "#currentvalue()"
  }
}


//second
{
  "final": {
    "#loop($.procedures)": {
      "codice_prest": "#currentvalueatpath($.codice_prest)",
      "name_paz": "#valueof(#xconcat(#currentvalueatpath($.start_paz),#currentvalueatpath($.id_paz),#currentvalueatpath($.end),.name))",
      "id_med": "#valueof(#xconcat(#currentvalueatpath($.start_med),#currentvalueatpath($.id_med),#currentvalueatpath($.end),.full_name))"
    }
  }
}
```

All of this just to be able to "concat" the jsonpath string without having "special" characters as arguments.

**Comment by mtdepippo** [comment]
@Courela It work it out!

I really want to thank you!!! Great job 👍
